In [ ]:
# !pip install optuna

Collecting optuna
  Downloading optuna-4.4.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in d:\anaconda\lib\site-packages (from optuna) (1.15.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in d:\anaconda\lib\site-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\lib\site-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in d:\anaconda\lib\site-packages (from optuna) (2.0.39)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in d:\anaconda\lib\site-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in d:\anaconda\lib\site-packages (from alembic>=1.5.0->optuna) (1.2.3)
Requirement already satisfied: typing-extensions>=4.12 in d:\anaconda\lib\site-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\anaconda\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.4.0-py3-none-any.whl (395 kB)
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna

   ---------------------------------------- 0/2 [colorlog]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   -------------------- ------------------- 1/2 [optuna]
   ---------------------------------------- 2/2 [optuna]

Successfully installed colorlog-6.9.0 optuna-4.4.0

In [3]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    #  using normal 
    # model.fit(X_train,y_train)
    # y_pred = model.predict(X_test)
    # accuracy = accuracy_score(y_test,y_pred)

    return score  # Return the accuracy score for Optuna to maximize
    # return accuracy

In [13]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-06-27 22:00:18,831] A new study created in memory with name: no-name-7010d99a-1b25-4084-a638-9df612ed7f44
[I 2025-06-27 22:00:19,321] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 82, 'max_depth': 16}. Best is trial 0 with value: 0.7635009310986964.
[I 2025-06-27 22:00:19,727] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 67, 'max_depth': 11}. Best is trial 1 with value: 0.7653631284916201.
[I 2025-06-27 22:00:20,222] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 102, 'max_depth': 11}. Best is trial 1 with value: 0.7653631284916201.
[I 2025-06-27 22:00:20,976] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 20}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-06-27 22:00:21,810] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 183, 'max_depth': 15}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-06-27 22:00:22,593] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 140, 'max_depth': 15}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-06-27 22:00:23,076] Trial 6 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 77, 'max_depth': 7}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:24,064] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 12}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:24,843] Trial 8 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 192, 'max_depth': 3}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:25,102] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 53, 'max_depth': 14}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:25,586] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 110, 'max_depth': 4}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:26,350] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 20}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:27,030] Trial 12 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 148, 'max_depth': 6}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:27,619] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 127, 'max_depth': 8}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:28,376] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 20}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:28,781] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 89, 'max_depth': 7}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:29,321] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 9}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:30,086] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 166, 'max_depth': 18}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:30,636] Trial 18 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 127, 'max_depth': 6}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:31,047] Trial 19 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 92, 'max_depth': 9}. Best is trial 6 with value: 0.7765363128491621.
[I 2025-06-27 22:00:31,362] Trial 20 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 69, 'max_depth': 18}. Best is trial 20 with value: 0.7783985102420857.
[I 2025-06-27 22:00:31,688] Trial 21 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:31,999] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:32,296] Trial 23 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 53, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:32,752] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 73, 'max_depth': 12}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:33,333] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 81, 'max_depth': 13}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:33,743] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:34,254] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:34,611] Trial 28 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 76, 'max_depth': 10}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:35,035] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 89, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:35,343] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 64, 'max_depth': 19}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:35,690] Trial 31 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 73, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:36,093] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:36,405] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 62, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:36,874] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 19}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:37,119] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:37,463] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 15}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:37,867] Trial 37 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 19}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:38,379] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:38,677] Trial 39 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 60, 'max_depth': 10}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:39,077] Trial 40 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 73, 'max_depth': 5}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:39,401] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:39,770] Trial 42 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 80, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:40,091] Trial 43 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:40,360] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:40,672] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 20}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:41,097] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 94, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:41,478] Trial 47 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 85, 'max_depth': 15}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:41,721] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 19}. Best is trial 21 with value: 0.7802607076350094.
[I 2025-06-27 22:00:42,260] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350094.

In [14]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350094
Best hyperparameters: {'n_estimators': 70, 'max_depth': 18}

In [15]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [16]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [25]:
# 1. Optimization History
plot_optimization_history(study).show()

In [18]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [19]:
# 3. Slice Plot
plot_slice(study).show()

In [24]:
# 4. Contour Plot
plot_contour(study).show()

In [23]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [22]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [26]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [27]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-06-27 22:34:51,321] A new study created in memory with name: no-name-4d436ea2-ebdf-48a4-aead-d125b7f50158
[I 2025-06-27 22:34:52,283] Trial 0 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 240, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.7523277467411545.
[I 2025-06-27 22:34:52,552] Trial 1 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 61, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.7635009310986964.
[I 2025-06-27 22:34:52,573] Trial 2 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6537295803774336, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:34:53,519] Trial 3 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 72, 'learning_rate': 0.14801579005943907, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:34:54,375] Trial 4 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 170, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:34:55,098] Trial 5 finished with value: 0.7225325884543762 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 50, 'learning_rate': 0.010471960962848904, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:34:56,219] Trial 6 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 266, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:34:57,262] Trial 7 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 254, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:00,381] Trial 8 finished with value: 0.7541899441340781 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 277, 'learning_rate': 0.102019432722361, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,062] Trial 9 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 151, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,090] Trial 10 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5281770015043797, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,119] Trial 11 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.44475145534621463, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,145] Trial 12 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6871844266306464, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,185] Trial 13 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 9.466678628068664, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,212] Trial 14 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8400704696428027, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,239] Trial 15 finished with value: 0.6852886405959032 and parameters: {'classifier': 'SVM', 'C': 89.6137035690192, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,268] Trial 16 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.1311954299762055, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,308] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.567880262012534, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,341] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.0605279834099473, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,378] Trial 19 finished with value: 0.7206703910614524 and parameters: {'classifier': 'SVM', 'C': 0.10740890894884447, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,406] Trial 20 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 1.7596310414790792, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,435] Trial 21 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6329917346796784, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,463] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8163101461019963, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,489] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22165872614871204, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:01,515] Trial 24 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 5.0796839195248795, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:02,569] Trial 25 finished with value: 0.7728119180633147 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 113, 'learning_rate': 0.017506919184677942, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:02,607] Trial 26 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3241572110587761, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:02,659] Trial 27 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1360988859665384, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:02,724] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.18507959961774, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:05,336] Trial 29 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 212, 'learning_rate': 0.04231002721302424, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:05,371] Trial 30 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 1.1709795973566652, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:05,438] Trial 31 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.619384752282195, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:05,473] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23143945043332642, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:05,501] Trial 33 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9429302096031615, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:05,534] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.1148162877939796, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:06,076] Trial 35 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 122, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:07,561] Trial 36 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 210, 'learning_rate': 0.2829124474823233, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:07,595] Trial 37 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.3287780916405284, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:08,964] Trial 38 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 294, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:08,990] Trial 39 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 0.5298749171451125, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:09,421] Trial 40 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 97, 'learning_rate': 0.04455852171216514, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:09,449] Trial 41 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8510775165986681, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:09,475] Trial 42 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8017169619545322, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:09,504] Trial 43 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4923378297308938, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:10,402] Trial 44 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 206, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:10,428] Trial 45 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4033725650667119, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:10,452] Trial 46 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19820555551133728, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:10,478] Trial 47 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.644127158931265, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:10,513] Trial 48 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.0994344623112973, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:11,129] Trial 49 finished with value: 0.761638733705773 and parameters: {'classifier': 'RandomForest', 'n_estimators': 157, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:11,157] Trial 50 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4986050023776142, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:11,181] Trial 51 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2536753438288039, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:11,205] Trial 52 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.43057105786475036, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7858472998137803.
[I 2025-06-27 22:35:11,230] Trial 53 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15761189316772267, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:11,267] Trial 54 finished with value: 0.7597765363128492 and parameters: {'classifier': 'SVM', 'C': 0.1775167870026914, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:11,294] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7448038821621824, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:11,321] Trial 56 finished with value: 0.6983240223463687 and parameters: {'classifier': 'SVM', 'C': 75.34205589287745, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,242] Trial 57 finished with value: 0.756052141527002 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 189, 'learning_rate': 0.02758824200650771, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,267] Trial 58 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.15829852172996942, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,294] Trial 59 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10222257785068418, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,320] Trial 60 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10008777505683944, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,345] Trial 61 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10266331141379614, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,370] Trial 62 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10298190319473524, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,394] Trial 63 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10229099111095205, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,417] Trial 64 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10280806417007453, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,439] Trial 65 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10141092239750393, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 53 with value: 0.7877094972067038.
[I 2025-06-27 22:35:13,466] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1286687560841135, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,510] Trial 67 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14090951992950287, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,564] Trial 68 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.14336363870587457, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,596] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14263398119625614, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,620] Trial 70 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1355548732431617, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,645] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14090090467215277, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,673] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14864273823260482, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,701] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1513683408577676, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,736] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15293638922367353, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:13,782] Trial 75 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.2717797451595473, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:14,459] Trial 76 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 137, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:15,152] Trial 77 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 87, 'learning_rate': 0.10256031829928912, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:15,178] Trial 78 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 0.1483868681415696, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:15,203] Trial 79 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2002036700228779, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:15,227] Trial 80 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3148659407083282, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.
[I 2025-06-27 22:35:15,276] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14300256830671326, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 66 with value: 0.7895716945996275.

In [28]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.1286687560841135, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [29]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.752328,2025-06-27 22:34:51.322805,2025-06-27 22:34:52.283946,0 days 00:00:00.961141,NaN,False,RandomForest,NaN,NaN,NaN,3.0,2.0,7.0,240.0,COMPLETE
1,1,0.763501,2025-06-27 22:34:52.284578,2025-06-27 22:34:52.551960,0 days 00:00:00.267382,NaN,False,RandomForest,NaN,NaN,NaN,19.0,1.0,6.0,61.0,COMPLETE
2,2,0.785847,2025-06-27 22:34:52.552582,2025-06-27 22:34:52.573683,0 days 00:00:00.021101,0.653730,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.748603,2025-06-27 22:34:52.574509,2025-06-27 22:34:53.519868,0 days 00:00:00.945359,NaN,NaN,GradientBoosting,NaN,NaN,0.148016,14.0,6.0,9.0,72.0,COMPLETE
4,4,0.772812,2025-06-27 22:34:53.520738,2025-06-27 22:34:54.374957,0 days 00:00:00.854219,NaN,False,RandomForest,NaN,NaN,NaN,10.0,4.0,10.0,170.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.787709,2025-06-27 22:35:16.347870,2025-06-27 22:35:16.369959,0 days 00:00:00.022089,0.172820,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.728119,2025-06-27 22:35:16.370491,2025-06-27 22:35:18.362057,0 days 00:00:01.991566,NaN,NaN,GradientBoosting,NaN,NaN,0.226980,16.0,7.0,9.0,186.0,COMPLETE
97,97,0.769088,2025-06-27 22:35:18.362589,2025-06-27 22:35:18.392593,0 days 00:00:00.030004,0.219586,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.785847,2025-06-27 22:35:18.393302,2025-06-27 22:35:18.452872,0 days 00:00:00.059570,13.050283,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.782123,2025-06-27 22:35:18.453467,2025-06-27 22:35:18.476609,0 days 00:00:00.023142,0.389221,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [30]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
RandomForest        12
GradientBoosting    10
Name: count, dtype: int64

In [31]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.748231
RandomForest        0.763966
SVM                 0.775462
Name: value, dtype: float64

In [32]:
# 1. Optimization History
plot_optimization_history(study).show()

In [33]:
# 3. Slice Plot
plot_slice(study).show()

In [34]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [39]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2025-06-27 22:41:23,126] A new study created in memory with name: no-name-61c9d2f2-3067-4b77-aaa2-95660dfc08ae

[0]	train-mlogloss:0.85256	eval-mlogloss:0.83854
[1]	train-mlogloss:0.75311	eval-mlogloss:0.73215
[2]	train-mlogloss:0.61918	eval-mlogloss:0.58824
[3]	train-mlogloss:0.50351	eval-mlogloss:0.47001
[4]	train-mlogloss:0.42179	eval-mlogloss:0.38616
[5]	train-mlogloss:0.35290	eval-mlogloss:0.31175
[6]	train-mlogloss:0.30099	eval-mlogloss:0.25590
[7]	train-mlogloss:0.26212	eval-mlogloss:0.21063
[8]	train-mlogloss:0.23140	eval-mlogloss:0.17703
[9]	train-mlogloss:0.20921	eval-mlogloss:0.15140
[10]	train-mlogloss:0.19442	eval-mlogloss:0.14030
[11]	train-mlogloss:0.18677	eval-mlogloss:0.13028
[12]	train-mlogloss:0.17732	eval-mlogloss:0.12010
[13]	train-mlogloss:0.17243	eval-mlogloss:0.11388
[14]	train-mlogloss:0.17131	eval-mlogloss:0.11466
[15]	train-mlogloss:0.17088	eval-mlogloss:0.11457
[16]	train-mlogloss:0.16952	eval-mlogloss:0.11293
[17]	train-mlogloss:0.16576	eval-mlogloss:0.10686
[18]	train-mlogloss:0.16494	eval-mlogloss:0.10739
[19]	train-mlogloss:0.16071	eval-mlogloss:0.10292
[20]	train-mlogloss:0.15979	eval-mlogloss:0.10329
[21]	train-mlogloss:0.15916	eval-mlogloss:0.10194
[22]	train-mlogloss:0.15626	eval-mlogloss:0.09778
[23]	train-mlogloss:0.15393	eval-mlogloss:0.09409
[24]	train-mlogloss:0.15387	eval-mlogloss:0.09364
[25]	train-mlogloss:0.15045	eval-mlogloss:0.08842
[26]	train-mlogloss:0.14923	eval-mlogloss:0.08826
[27]	train-mlogloss:0.14931	eval-mlogloss:0.08865
[28]	train-mlogloss:0.14733	eval-mlogloss:0.08573
[29]	train-mlogloss:0.14670	eval-mlogloss:0.08551
[30]	train-mlogloss:0.14583	eval-mlogloss:0.08596
[31]	train-mlogloss:0.14546	eval-mlogloss:0.08541
[32]	train-mlogloss:0.14550	eval-mlogloss:0.08583
[33]	train-mlogloss:0.14514	eval-mlogloss:0.08607
[34]	train-mlogloss:0.14470	eval-mlogloss:0.08450
[35]	train-mlogloss:0.14443	eval-mlogloss:0.08421
[36]	train-mlogloss:0.14409	eval-mlogloss:0.08409
[37]	train-mlogloss:0.14223	eval-mlogloss:0.08226
[38]	train-mlogloss:0.14232	eval-mlogloss:0.08240
[39]	train-mlogloss:0.14225	eval-mlogloss:0.08243
[40]	train-mlogloss:0.14226	eval-mlogloss:0.08247
[41]	train-mlogloss:0.14198	eval-mlogloss:0.08208
[42]	train-mlogloss:0.14202	eval-mlogloss:0.08210
[43]	train-mlogloss:0.14015	eval-mlogloss:0.07978
[44]	train-mlogloss:0.13976	eval-mlogloss:0.07778
[45]	train-mlogloss:0.13942	eval-mlogloss:0.07752
[46]	train-mlogloss:0.13913	eval-mlogloss:0.07682
[47]	train-mlogloss:0.13912	eval-mlogloss:0.07689
[48]	train-mlogloss:0.13908	eval-mlogloss:0.07646
[49]	train-mlogloss:0.13898	eval-mlogloss:0.07627
[50]	train-mlogloss:0.13902	eval-mlogloss:0.07635
[51]	train-mlogloss:0.13890	eval-mlogloss:0.07597
[52]	train-mlogloss:0.13850	eval-mlogloss:0.07589
[53]	train-mlogloss:0.13856	eval-mlogloss:0.07608
[54]	train-mlogloss:0.13850	eval-mlogloss:0.07584
[55]	train-mlogloss:0.13798	eval-mlogloss:0.07603
[56]	train-mlogloss:0.13772	eval-mlogloss:0.07586
[57]	train-mlogloss:0.13766	eval-mlogloss:0.07593
[58]	train-mlogloss:0.13772	eval-mlogloss:0.07587
[59]	train-mlogloss:0.13741	eval-mlogloss:0.07579
[60]	train-mlogloss:0.13728	eval-mlogloss:0.07607
[61]	train-mlogloss:0.13705	eval-mlogloss:0.07595
[62]	train-mlogloss:0.13708	eval-mlogloss:0.07618
[63]	train-mlogloss:0.13686	eval-mlogloss:0.07414
[64]	train-mlogloss:0.13678	eval-mlogloss:0.07390
[65]	train-mlogloss:0.13682	eval-mlogloss:0.07345
[66]	train-mlogloss:0.13641	eval-mlogloss:0.07257
[67]	train-mlogloss:0.13615	eval-mlogloss:0.07246
[68]	train-mlogloss:0.13600	eval-mlogloss:0.07244
[69]	train-mlogloss:0.13447	eval-mlogloss:0.07049
[70]	train-mlogloss:0.13444	eval-mlogloss:0.07040
[71]	train-mlogloss:0.13458	eval-mlogloss:0.07059
[72]	train-mlogloss:0.13456	eval-mlogloss:0.07066
[73]	train-mlogloss:0.13449	eval-mlogloss:0.07007
[74]	train-mlogloss:0.13442	eval-mlogloss:0.07029
[75]	train-mlogloss:0.13445	eval-mlogloss:0.07060
[76]	train-mlogloss:0.13453	eval-mlogloss:0.07079
[77]	train-mlogloss:0.13446	eval-mlogloss:0.07090
[78]	train-mlogloss:0.13473	eval-mlogloss:0.07185
[79]	train-mlogloss:0.13461	eval-mlogloss:0.07165
[80]	train-mlogloss:0.13463	eval-mlogloss:0.07142
[81]	train-mlogloss:0.13454	eval-mlogloss:0.07155
[82]	train-mlogloss:0.13456	eval-mlogloss:0.07166
[83]	train-mlogloss:0.13451	eval-mlogloss:0.07192
[84]	train-mlogloss:0.13435	eval-mlogloss:0.07186
[85]	train-mlogloss:0.13426	eval-mlogloss:0.07176
[86]	train-mlogloss:0.13440	eval-mlogloss:0.07229
[87]	train-mlogloss:0.13434	eval-mlogloss:0.07229
[88]	train-mlogloss:0.13421	eval-mlogloss:0.07220
[89]	train-mlogloss:0.13300	eval-mlogloss:0.06961
[90]	train-mlogloss:0.13298	eval-mlogloss:0.06970
[91]	train-mlogloss:0.13297	eval-mlogloss:0.06975
[92]	train-mlogloss:0.13274	eval-mlogloss:0.06962
[93]	train-mlogloss:0.13253	eval-mlogloss:0.06953
[94]	train-mlogloss:0.13256	eval-mlogloss:0.06942
[95]	train-mlogloss:0.13260	eval-mlogloss:0.06952
[96]	train-mlogloss:0.13279	eval-mlogloss:0.06951
[97]	train-mlogloss:0.13256	eval-mlogloss:0.06922
[98]	train-mlogloss:0.13281	eval-mlogloss:0.06974
[99]	train-mlogloss:0.13236	eval-mlogloss:0.06913
[100]	train-mlogloss:0.13216	eval-mlogloss:0.06852
[101]	train-mlogloss:0.13192	eval-mlogloss:0.06827
[102]	train-mlogloss:0.13180	eval-mlogloss:0.06807
[103]	train-mlogloss:0.13175	eval-mlogloss:0.06806
[104]	train-mlogloss:0.13175	eval-mlogloss:0.06758
[105]	train-mlogloss:0.13166	eval-mlogloss:0.06724
[106]	train-mlogloss:0.13159	eval-mlogloss:0.06742
[107]	train-mlogloss:0.13176	eval-mlogloss:0.06798
[108]	train-mlogloss:0.13158	eval-mlogloss:0.06762
[109]	train-mlogloss:0.13148	eval-mlogloss:0.06750
[110]	train-mlogloss:0.13159	eval-mlogloss:0.06772
[111]	train-mlogloss:0.13179	eval-mlogloss:0.06844
[112]	train-mlogloss:0.13176	eval-mlogloss:0.06848
[113]	train-mlogloss:0.13171	eval-mlogloss:0.06829
[114]	train-mlogloss:0.13144	eval-mlogloss:0.06778
[115]	train-mlogloss:0.13146	eval-mlogloss:0.06777
[116]	train-mlogloss:0.13151	eval-mlogloss:0.06791
[117]	train-mlogloss:0.13127	eval-mlogloss:0.06716
[118]	train-mlogloss:0.13127	eval-mlogloss:0.06740
[119]	train-mlogloss:0.13098	eval-mlogloss:0.06733
[120]	train-mlogloss:0.13092	eval-mlogloss:0.06709
[121]	train-mlogloss:0.13104	eval-mlogloss:0.06755
[122]	train-mlogloss:0.13106	eval-mlogloss:0.06771
[123]	train-mlogloss:0.13091	eval-mlogloss:0.06759
[124]	train-mlogloss:0.13077	eval-mlogloss:0.06737
[125]	train-mlogloss:0.13074	eval-mlogloss:0.06740
[126]	train-mlogloss:0.13071	eval-mlogloss:0.06683
[127]	train-mlogloss:0.13085	eval-mlogloss:0.06682
[128]	train-mlogloss:0.13099	eval-mlogloss:0.06709
[129]	train-mlogloss:0.13090	eval-mlogloss:0.06714
[130]	train-mlogloss:0.13088	eval-mlogloss:0.06721
[131]	train-mlogloss:0.13076	eval-mlogloss:0.06722
[132]	train-mlogloss:0.13053	eval-mlogloss:0.06662
[133]	train-mlogloss:0.13050	eval-mlogloss:0.06670
[134]	train-mlogloss:0.13051	eval-mlogloss:0.06684
[135]	train-mlogloss:0.13046	eval-mlogloss:0.06677
[136]	train-mlogloss:0.13049	eval-mlogloss:0.06691
[137]	train-mlogloss:0.13029	eval-mlogloss:0.06641
[138]	train-mlogloss:0.13016	eval-mlogloss:0.06578
[139]	train-mlogloss:0.13007	eval-mlogloss:0.06577
[140]	train-mlogloss:0.12999	eval-mlogloss:0.06575
[141]	train-mlogloss:0.13008	eval-mlogloss:0.06592
[142]	train-mlogloss:0.13032	eval-mlogloss:0.06626
[143]	train-mlogloss:0.13024	eval-mlogloss:0.06622
[144]	train-mlogloss:0.13029	eval-mlogloss:0.06587
[145]	train-mlogloss:0.13057	eval-mlogloss:0.06613
[146]	train-mlogloss:0.13031	eval-mlogloss:0.06589
[147]	train-mlogloss:0.13009	eval-mlogloss:0.06561
[148]	train-mlogloss:0.12999	eval-mlogloss:0.06562
[149]	train-mlogloss:0.12999	eval-mlogloss:0.06559
[150]	train-mlogloss:0.12989	eval-mlogloss:0.06541
[151]	train-mlogloss:0.12990	eval-mlogloss:0.06524
[152]	train-mlogloss:0.12992	eval-mlogloss:0.06531
[153]	train-mlogloss:0.12996	eval-mlogloss:0.06504
[154]	train-mlogloss:0.12992	eval-mlogloss:0.06453
[155]	train-mlogloss:0.13017	eval-mlogloss:0.06441
[156]	train-mlogloss:0.13020	eval-mlogloss:0.06435
[157]	train-mlogloss:0.13015	eval-mlogloss:0.06439
[158]	train-mlogloss:0.13007	eval-mlogloss:0.06439
[159]	train-mlogloss:0.12974	eval-mlogloss:0.06447
[160]	train-mlogloss:0.12973	eval-mlogloss:0.06453
[161]	train-mlogloss:0.12970	eval-mlogloss:0.06461
[162]	train-mlogloss:0.12969	eval-mlogloss:0.06465
[163]	train-mlogloss:0.12967	eval-mlogloss:0.06486
[164]	train-mlogloss:0.12971	eval-mlogloss:0.06511
[165]	train-mlogloss:0.12968	eval-mlogloss:0.06523
[166]	train-mlogloss:0.12968	eval-mlogloss:0.06507
[167]	train-mlogloss:0.12969	eval-mlogloss:0.06506
[168]	train-mlogloss:0.12969	eval-mlogloss:0.06499
[169]	train-mlogloss:0.12960	eval-mlogloss:0.06492
[170]	train-mlogloss:0.12957	eval-mlogloss:0.06475
[171]	train-mlogloss:0.12954	eval-mlogloss:0.06524
[172]	train-mlogloss:0.12949	eval-mlogloss:0.06509
[173]	train-mlogloss:0.12936	eval-mlogloss:0.06516
[174]	train-mlogloss:0.12943	eval-mlogloss:0.06561
[175]	train-mlogloss:0.12943	eval-mlogloss:0.06555
[176]	train-mlogloss:0.12942	eval-mlogloss:0.06532
[177]	train-mlogloss:0.12939	eval-mlogloss:0.06526
[178]	train-mlogloss:0.12926	eval-mlogloss:0.06516
[179]	train-mlogloss:0.12930	eval-mlogloss:0.06504
[180]	train-mlogloss:0.12941	eval-mlogloss:0.06394
[181]	train-mlogloss:0.12934	eval-mlogloss:0.06396
[182]	train-mlogloss:0.12934	eval-mlogloss:0.06380
[183]	train-mlogloss:0.12925	eval-mlogloss:0.06402
[184]	train-mlogloss:0.12918	eval-mlogloss:0.06405
[185]	train-mlogloss:0.12918	eval-mlogloss:0.06456
[186]	train-mlogloss:0.12894	eval-mlogloss:0.06418
[187]	train-mlogloss:0.12891	eval-mlogloss:0.06430
[188]	train-mlogloss:0.12893	eval-mlogloss:0.06438
[189]	train-mlogloss:0.12896	eval-mlogloss:0.06457
[190]	train-mlogloss:0.12898	eval-mlogloss:0.06462
[191]	train-mlogloss:0.12891	eval-mlogloss:0.06458
[192]	train-mlogloss:0.12893	eval-mlogloss:0.06470
[193]	train-mlogloss:0.12894	eval-mlogloss:0.06467
[194]	train-mlogloss:0.12902	eval-mlogloss:0.06486
[195]	train-mlogloss:0.12889	eval-mlogloss:0.06475
[196]	train-mlogloss:0.12892	eval-mlogloss:0.06491
[197]	train-mlogloss:0.12899	eval-mlogloss:0.06475
[198]	train-mlogloss:0.12912	eval-mlogloss:0.06456
[199]	train-mlogloss:0.12913	eval-mlogloss:0.06425
[200]	train-mlogloss:0.12906	eval-mlogloss:0.06420
[201]	train-mlogloss:0.12924	eval-mlogloss:0.06411
[202]	train-mlogloss:0.12919	eval-mlogloss:0.06419
[203]	train-mlogloss:0.12910	eval-mlogloss:0.06478
[204]	train-mlogloss:0.12904	eval-mlogloss:0.06479
[205]	train-mlogloss:0.12895	eval-mlogloss:0.06474
[206]	train-mlogloss:0.12897	eval-mlogloss:0.06501
[207]	train-mlogloss:0.12895	eval-mlogloss:0.06503
[208]	train-mlogloss:0.12890	eval-mlogloss:0.06532
[209]	train-mlogloss:0.12886	eval-mlogloss:0.06524
[210]	train-mlogloss:0.12887	eval-mlogloss:0.06472
[211]	train-mlogloss:0.12881	eval-mlogloss:0.06454

[I 2025-06-27 22:41:24,052] Trial 0 finished with value: 1.0 and parameters: {'lambda': 3.8824678601102815e-06, 'alpha': 6.721789534672643e-08, 'eta': 0.2070189698398038, 'gamma': 0.0017096393792721705, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.7134122274307897, 'colsample_bytree': 0.554105712470375}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.06150	eval-mlogloss:1.06093
[1]	train-mlogloss:1.02826	eval-mlogloss:1.02331
[2]	train-mlogloss:0.99488	eval-mlogloss:0.98720
[3]	train-mlogloss:0.96045	eval-mlogloss:0.95136
[4]	train-mlogloss:0.92960	eval-mlogloss:0.91955
[5]	train-mlogloss:0.89840	eval-mlogloss:0.88623
[6]	train-mlogloss:0.86923	eval-mlogloss:0.85432
[7]	train-mlogloss:0.84354	eval-mlogloss:0.82864
[8]	train-mlogloss:0.81780	eval-mlogloss:0.80099
[9]	train-mlogloss:0.79198	eval-mlogloss:0.77436
[10]	train-mlogloss:0.76857	eval-mlogloss:0.75047
[11]	train-mlogloss:0.74560	eval-mlogloss:0.72595
[12]	train-mlogloss:0.72343	eval-mlogloss:0.70217
[13]	train-mlogloss:0.70192	eval-mlogloss:0.68009
[14]	train-mlogloss:0.68162	eval-mlogloss:0.65823
[15]	train-mlogloss:0.66186	eval-mlogloss:0.63700
[16]	train-mlogloss:0.64253	eval-mlogloss:0.61636
[17]	train-mlogloss:0.62467	eval-mlogloss:0.59701
[18]	train-mlogloss:0.60740	eval-mlogloss:0.57871
[19]	train-mlogloss:0.59022	eval-mlogloss:0.56076
[20]	train-mlogloss:0.57481	eval-mlogloss:0.54450
[21]	train-mlogloss:0.56209	eval-mlogloss:0.53139
[22]	train-mlogloss:0.54664	eval-mlogloss:0.51495
[23]	train-mlogloss:0.53302	eval-mlogloss:0.50158
[24]	train-mlogloss:0.51847	eval-mlogloss:0.48580
[25]	train-mlogloss:0.50575	eval-mlogloss:0.47129
[26]	train-mlogloss:0.49252	eval-mlogloss:0.45721
[27]	train-mlogloss:0.48006	eval-mlogloss:0.44472
[28]	train-mlogloss:0.46730	eval-mlogloss:0.43083
[29]	train-mlogloss:0.45567	eval-mlogloss:0.41825
[30]	train-mlogloss:0.44504	eval-mlogloss:0.40739
[31]	train-mlogloss:0.43411	eval-mlogloss:0.39543
[32]	train-mlogloss:0.42354	eval-mlogloss:0.38444
[33]	train-mlogloss:0.41312	eval-mlogloss:0.37304
[34]	train-mlogloss:0.40354	eval-mlogloss:0.36316
[35]	train-mlogloss:0.39402	eval-mlogloss:0.35241
[36]	train-mlogloss:0.38512	eval-mlogloss:0.34295
[37]	train-mlogloss:0.37657	eval-mlogloss:0.33388
[38]	train-mlogloss:0.36807	eval-mlogloss:0.32495
[39]	train-mlogloss:0.35939	eval-mlogloss:0.31616
[40]	train-mlogloss:0.35149	eval-mlogloss:0.30809
[41]	train-mlogloss:0.34354	eval-mlogloss:0.29953
[42]	train-mlogloss:0.33574	eval-mlogloss:0.29132
[43]	train-mlogloss:0.32868	eval-mlogloss:0.28378
[44]	train-mlogloss:0.32134	eval-mlogloss:0.27619
[45]	train-mlogloss:0.31392	eval-mlogloss:0.26804
[46]	train-mlogloss:0.30684	eval-mlogloss:0.26046
[47]	train-mlogloss:0.30056	eval-mlogloss:0.25381
[48]	train-mlogloss:0.29458	eval-mlogloss:0.24787
[49]	train-mlogloss:0.28791	eval-mlogloss:0.24113
[50]	train-mlogloss:0.28202	eval-mlogloss:0.23458
[51]	train-mlogloss:0.27720	eval-mlogloss:0.22945
[52]	train-mlogloss:0.27158	eval-mlogloss:0.22310
[53]	train-mlogloss:0.26645	eval-mlogloss:0.21749
[54]	train-mlogloss:0.26140	eval-mlogloss:0.21309
[55]	train-mlogloss:0.25593	eval-mlogloss:0.20808
[56]	train-mlogloss:0.25104	eval-mlogloss:0.20316
[57]	train-mlogloss:0.24672	eval-mlogloss:0.19863
[58]	train-mlogloss:0.24184	eval-mlogloss:0.19366
[59]	train-mlogloss:0.23803	eval-mlogloss:0.18931
[60]	train-mlogloss:0.23416	eval-mlogloss:0.18546
[61]	train-mlogloss:0.23032	eval-mlogloss:0.18135
[62]	train-mlogloss:0.22602	eval-mlogloss:0.17663
[63]	train-mlogloss:0.22177	eval-mlogloss:0.17248
[64]	train-mlogloss:0.21852	eval-mlogloss:0.16892
[65]	train-mlogloss:0.21510	eval-mlogloss:0.16533
[66]	train-mlogloss:0.21160	eval-mlogloss:0.16084
[67]	train-mlogloss:0.20826	eval-mlogloss:0.15748
[68]	train-mlogloss:0.20501	eval-mlogloss:0.15366
[69]	train-mlogloss:0.20173	eval-mlogloss:0.15071
[70]	train-mlogloss:0.19869	eval-mlogloss:0.14730
[71]	train-mlogloss:0.19585	eval-mlogloss:0.14391
[72]	train-mlogloss:0.19400	eval-mlogloss:0.14193
[73]	train-mlogloss:0.19069	eval-mlogloss:0.13830
[74]	train-mlogloss:0.18795	eval-mlogloss:0.13545
[75]	train-mlogloss:0.18484	eval-mlogloss:0.13265
[76]	train-mlogloss:0.18221	eval-mlogloss:0.12951
[77]	train-mlogloss:0.17963	eval-mlogloss:0.12686
[78]	train-mlogloss:0.17758	eval-mlogloss:0.12502
[79]	train-mlogloss:0.17576	eval-mlogloss:0.12248
[80]	train-mlogloss:0.17389	eval-mlogloss:0.12003
[81]	train-mlogloss:0.17192	eval-mlogloss:0.11804
[82]	train-mlogloss:0.16999	eval-mlogloss:0.11604
[83]	train-mlogloss:0.16842	eval-mlogloss:0.11409
[84]	train-mlogloss:0.16654	eval-mlogloss:0.11195
[85]	train-mlogloss:0.16551	eval-mlogloss:0.11094
[86]	train-mlogloss:0.16491	eval-mlogloss:0.11005
[87]	train-mlogloss:0.16366	eval-mlogloss:0.10881
[88]	train-mlogloss:0.16173	eval-mlogloss:0.10663
[89]	train-mlogloss:0.15991	eval-mlogloss:0.10452
[90]	train-mlogloss:0.15864	eval-mlogloss:0.10288
[91]	train-mlogloss:0.15801	eval-mlogloss:0.10173
[92]	train-mlogloss:0.15723	eval-mlogloss:0.10069
[93]	train-mlogloss:0.15706	eval-mlogloss:0.10042
[94]	train-mlogloss:0.15625	eval-mlogloss:0.09954
[95]	train-mlogloss:0.15614	eval-mlogloss:0.09948
[96]	train-mlogloss:0.15529	eval-mlogloss:0.09830
[97]	train-mlogloss:0.15464	eval-mlogloss:0.09723
[98]	train-mlogloss:0.15311	eval-mlogloss:0.09539
[99]	train-mlogloss:0.15287	eval-mlogloss:0.09551
[100]	train-mlogloss:0.15199	eval-mlogloss:0.09461
[101]	train-mlogloss:0.15043	eval-mlogloss:0.09286
[102]	train-mlogloss:0.14996	eval-mlogloss:0.09212
[103]	train-mlogloss:0.14942	eval-mlogloss:0.09121
[104]	train-mlogloss:0.14900	eval-mlogloss:0.09041
[105]	train-mlogloss:0.14836	eval-mlogloss:0.08955
[106]	train-mlogloss:0.14783	eval-mlogloss:0.08870
[107]	train-mlogloss:0.14742	eval-mlogloss:0.08809
[108]	train-mlogloss:0.14734	eval-mlogloss:0.08810
[109]	train-mlogloss:0.14640	eval-mlogloss:0.08717
[110]	train-mlogloss:0.14609	eval-mlogloss:0.08671
[111]	train-mlogloss:0.14565	eval-mlogloss:0.08601
[112]	train-mlogloss:0.14538	eval-mlogloss:0.08560
[113]	train-mlogloss:0.14509	eval-mlogloss:0.08477
[114]	train-mlogloss:0.14496	eval-mlogloss:0.08432
[115]	train-mlogloss:0.14487	eval-mlogloss:0.08411
[116]	train-mlogloss:0.14483	eval-mlogloss:0.08408
[117]	train-mlogloss:0.14412	eval-mlogloss:0.08288
[118]	train-mlogloss:0.14372	eval-mlogloss:0.08250
[119]	train-mlogloss:0.14300	eval-mlogloss:0.08179
[120]	train-mlogloss:0.14272	eval-mlogloss:0.08164
[121]	train-mlogloss:0.14232	eval-mlogloss:0.08165
[122]	train-mlogloss:0.14197	eval-mlogloss:0.08109
[123]	train-mlogloss:0.14171	eval-mlogloss:0.08115
[124]	train-mlogloss:0.14131	eval-mlogloss:0.08047
[125]	train-mlogloss:0.14098	eval-mlogloss:0.07998
[126]	train-mlogloss:0.14062	eval-mlogloss:0.07993
[127]	train-mlogloss:0.14054	eval-mlogloss:0.07986
[128]	train-mlogloss:0.14044	eval-mlogloss:0.07980
[129]	train-mlogloss:0.13977	eval-mlogloss:0.07884
[130]	train-mlogloss:0.13984	eval-mlogloss:0.07891
[131]	train-mlogloss:0.13971	eval-mlogloss:0.07864
[132]	train-mlogloss:0.13937	eval-mlogloss:0.07832
[133]	train-mlogloss:0.13880	eval-mlogloss:0.07750
[134]	train-mlogloss:0.13879	eval-mlogloss:0.07753
[135]	train-mlogloss:0.13837	eval-mlogloss:0.07690
[136]	train-mlogloss:0.13802	eval-mlogloss:0.07630
[137]	train-mlogloss:0.13766	eval-mlogloss:0.07565
[138]	train-mlogloss:0.13763	eval-mlogloss:0.07567
[139]	train-mlogloss:0.13738	eval-mlogloss:0.07572
[140]	train-mlogloss:0.13723	eval-mlogloss:0.07560
[141]	train-mlogloss:0.13712	eval-mlogloss:0.07549
[142]	train-mlogloss:0.13715	eval-mlogloss:0.07545
[143]	train-mlogloss:0.13673	eval-mlogloss:0.07482
[144]	train-mlogloss:0.13671	eval-mlogloss:0.07484
[145]	train-mlogloss:0.13673	eval-mlogloss:0.07483
[146]	train-mlogloss:0.13651	eval-mlogloss:0.07443
[147]	train-mlogloss:0.13612	eval-mlogloss:0.07393
[148]	train-mlogloss:0.13611	eval-mlogloss:0.07391
[149]	train-mlogloss:0.13579	eval-mlogloss:0.07360
[150]	train-mlogloss:0.13575	eval-mlogloss:0.07374
[151]	train-mlogloss:0.13530	eval-mlogloss:0.07330
[152]	train-mlogloss:0.13533	eval-mlogloss:0.07336
[153]	train-mlogloss:0.13495	eval-mlogloss:0.07299
[154]	train-mlogloss:0.13486	eval-mlogloss:0.07279
[155]	train-mlogloss:0.13468	eval-mlogloss:0.07242
[156]	train-mlogloss:0.13452	eval-mlogloss:0.07268
[157]	train-mlogloss:0.13429	eval-mlogloss:0.07229
[158]	train-mlogloss:0.13429	eval-mlogloss:0.07214
[159]	train-mlogloss:0.13415	eval-mlogloss:0.07205
[160]	train-mlogloss:0.13412	eval-mlogloss:0.07199
[161]	train-mlogloss:0.13403	eval-mlogloss:0.07178
[162]	train-mlogloss:0.13372	eval-mlogloss:0.07184
[163]	train-mlogloss:0.13340	eval-mlogloss:0.07157
[164]	train-mlogloss:0.13337	eval-mlogloss:0.07154
[165]	train-mlogloss:0.13307	eval-mlogloss:0.07176
[166]	train-mlogloss:0.13288	eval-mlogloss:0.07143
[167]	train-mlogloss:0.13290	eval-mlogloss:0.07163
[168]	train-mlogloss:0.13269	eval-mlogloss:0.07177
[169]	train-mlogloss:0.13230	eval-mlogloss:0.07140
[170]	train-mlogloss:0.13229	eval-mlogloss:0.07137
[171]	train-mlogloss:0.13229	eval-mlogloss:0.07119
[172]	train-mlogloss:0.13223	eval-mlogloss:0.07116
[173]	train-mlogloss:0.13189	eval-mlogloss:0.07062
[174]	train-mlogloss:0.13153	eval-mlogloss:0.06999
[175]	train-mlogloss:0.13111	eval-mlogloss:0.06957
[176]	train-mlogloss:0.13095	eval-mlogloss:0.06924
[177]	train-mlogloss:0.13064	eval-mlogloss:0.06876
[178]	train-mlogloss:0.13045	eval-mlogloss:0.06899
[179]	train-mlogloss:0.13022	eval-mlogloss:0.06852
[180]	train-mlogloss:0.13026	eval-mlogloss:0.06820
[181]	train-mlogloss:0.13024	eval-mlogloss:0.06816
[182]	train-mlogloss:0.13012	eval-mlogloss:0.06767
[183]	train-mlogloss:0.13016	eval-mlogloss:0.06763
[184]	train-mlogloss:0.13011	eval-mlogloss:0.06767
[185]	train-mlogloss:0.13014	eval-mlogloss:0.06771
[186]	train-mlogloss:0.12984	eval-mlogloss:0.06769
[187]	train-mlogloss:0.12981	eval-mlogloss:0.06766
[188]	train-mlogloss:0.12984	eval-mlogloss:0.06770
[189]	train-mlogloss:0.12979	eval-mlogloss:0.06769
[190]	train-mlogloss:0.12980	eval-mlogloss:0.06777
[191]	train-mlogloss:0.12977	eval-mlogloss:0.06772
[192]	train-mlogloss:0.12968	eval-mlogloss:0.06767
[193]	train-mlogloss:0.12957	eval-mlogloss:0.06753
[194]	train-mlogloss:0.12936	eval-mlogloss:0.06762
[195]	train-mlogloss:0.12935	eval-mlogloss:0.06781
[196]	train-mlogloss:0.12930	eval-mlogloss:0.06779
[197]	train-mlogloss:0.12909	eval-mlogloss:0.06753
[198]	train-mlogloss:0.12902	eval-mlogloss:0.06758
[199]	train-mlogloss:0.12868	eval-mlogloss:0.06716
[200]	train-mlogloss:0.12863	eval-mlogloss:0.06706
[201]	train-mlogloss:0.12849	eval-mlogloss:0.06671
[202]	train-mlogloss:0.12849	eval-mlogloss:0.06673
[203]	train-mlogloss:0.12841	eval-mlogloss:0.06655
[204]	train-mlogloss:0.12820	eval-mlogloss:0.06658
[205]	train-mlogloss:0.12801	eval-mlogloss:0.06659
[206]	train-mlogloss:0.12798	eval-mlogloss:0.06661
[207]	train-mlogloss:0.12794	eval-mlogloss:0.06659
[208]	train-mlogloss:0.12776	eval-mlogloss:0.06636
[209]	train-mlogloss:0.12747	eval-mlogloss:0.06592
[210]	train-mlogloss:0.12742	eval-mlogloss:0.06584
[211]	train-mlogloss:0.12733	eval-mlogloss:0.06586
[212]	train-mlogloss:0.12732	eval-mlogloss:0.06556
[213]	train-mlogloss:0.12726	eval-mlogloss:0.06553
[214]	train-mlogloss:0.12727	eval-mlogloss:0.06564
[215]	train-mlogloss:0.12711	eval-mlogloss:0.06576
[216]	train-mlogloss:0.12685	eval-mlogloss:0.06523
[217]	train-mlogloss:0.12681	eval-mlogloss:0.06514
[218]	train-mlogloss:0.12664	eval-mlogloss:0.06484
[219]	train-mlogloss:0.12659	eval-mlogloss:0.06478
[220]	train-mlogloss:0.12658	eval-mlogloss:0.06492
[221]	train-mlogloss:0.12656	eval-mlogloss:0.06491
[222]	train-mlogloss:0.12646	eval-mlogloss:0.06480
[223]	train-mlogloss:0.12643	eval-mlogloss:0.06477
[224]	train-mlogloss:0.12597	eval-mlogloss:0.06429
[225]	train-mlogloss:0.12597	eval-mlogloss:0.06434
[226]	train-mlogloss:0.12597	eval-mlogloss:0.06433
[227]	train-mlogloss:0.12586	eval-mlogloss:0.06418
[228]	train-mlogloss:0.12563	eval-mlogloss:0.06399
[229]	train-mlogloss:0.12567	eval-mlogloss:0.06409
[230]	train-mlogloss:0.12563	eval-mlogloss:0.06402
[231]	train-mlogloss:0.12568	eval-mlogloss:0.06409
[232]	train-mlogloss:0.12565	eval-mlogloss:0.06408
[233]	train-mlogloss:0.12543	eval-mlogloss:0.06416
[234]	train-mlogloss:0.12543	eval-mlogloss:0.06422
[235]	train-mlogloss:0.12543	eval-mlogloss:0.06427
[236]	train-mlogloss:0.12545	eval-mlogloss:0.06428
[237]	train-mlogloss:0.12544	eval-mlogloss:0.06396
[238]	train-mlogloss:0.12532	eval-mlogloss:0.06391
[239]	train-mlogloss:0.12524	eval-mlogloss:0.06380
[240]	train-mlogloss:0.12525	eval-mlogloss:0.06357
[241]	train-mlogloss:0.12508	eval-mlogloss:0.06386
[242]	train-mlogloss:0.12508	eval-mlogloss:0.06388
[243]	train-mlogloss:0.12508	eval-mlogloss:0.06389
[244]	train-mlogloss:0.12508	eval-mlogloss:0.06387
[245]	train-mlogloss:0.12505	eval-mlogloss:0.06386
[246]	train-mlogloss:0.12503	eval-mlogloss:0.06394
[247]	train-mlogloss:0.12491	eval-mlogloss:0.06377
[248]	train-mlogloss:0.12489	eval-mlogloss:0.06345
[249]	train-mlogloss:0.12488	eval-mlogloss:0.06348
[250]	train-mlogloss:0.12482	eval-mlogloss:0.06342
[251]	train-mlogloss:0.12479	eval-mlogloss:0.06338
[252]	train-mlogloss:0.12472	eval-mlogloss:0.06323
[253]	train-mlogloss:0.12465	eval-mlogloss:0.06319
[254]	train-mlogloss:0.12465	eval-mlogloss:0.06340
[255]	train-mlogloss:0.12447	eval-mlogloss:0.06365
[256]	train-mlogloss:0.12438	eval-mlogloss:0.06358
[257]	train-mlogloss:0.12433	eval-mlogloss:0.06351
[258]	train-mlogloss:0.12417	eval-mlogloss:0.06329
[259]	train-mlogloss:0.12407	eval-mlogloss:0.06310
[260]	train-mlogloss:0.12396	eval-mlogloss:0.06302
[261]	train-mlogloss:0.12391	eval-mlogloss:0.06290
[262]	train-mlogloss:0.12375	eval-mlogloss:0.06258
[263]	train-mlogloss:0.12370	eval-mlogloss:0.06244
[264]	train-mlogloss:0.12370	eval-mlogloss:0.06245
[265]	train-mlogloss:0.12371	eval-mlogloss:0.06247
[266]	train-mlogloss:0.12372	eval-mlogloss:0.06244
[267]	train-mlogloss:0.12345	eval-mlogloss:0.06213
[268]	train-mlogloss:0.12335	eval-mlogloss:0.06183
[269]	train-mlogloss:0.12329	eval-mlogloss:0.06180
[270]	train-mlogloss:0.12325	eval-mlogloss:0.06165
[271]	train-mlogloss:0.12320	eval-mlogloss:0.06164
[272]	train-mlogloss:0.12319	eval-mlogloss:0.06168
[273]	train-mlogloss:0.12313	eval-mlogloss:0.06168
[274]	train-mlogloss:0.12313	eval-mlogloss:0.06168
[275]	train-mlogloss:0.12301	eval-mlogloss:0.06163
[276]	train-mlogloss:0.12301	eval-mlogloss:0.06165
[277]	train-mlogloss:0.12302	eval-mlogloss:0.06179
[278]	train-mlogloss:0.12290	eval-mlogloss:0.06184
[279]	train-mlogloss:0.12282	eval-mlogloss:0.06180
[280]	train-mlogloss:0.12254	eval-mlogloss:0.06155
[281]	train-mlogloss:0.12249	eval-mlogloss:0.06145
[282]	train-mlogloss:0.12247	eval-mlogloss:0.06148
[283]	train-mlogloss:0.12236	eval-mlogloss:0.06130
[284]	train-mlogloss:0.12236	eval-mlogloss:0.06131
[285]	train-mlogloss:0.12238	eval-mlogloss:0.06132
[286]	train-mlogloss:0.12231	eval-mlogloss:0.06135
[287]	train-mlogloss:0.12209	eval-mlogloss:0.06120
[288]	train-mlogloss:0.12213	eval-mlogloss:0.06134
[289]	train-mlogloss:0.12205	eval-mlogloss:0.06140
[290]	train-mlogloss:0.12205	eval-mlogloss:0.06153
[291]	train-mlogloss:0.12182	eval-mlogloss:0.06108
[292]	train-mlogloss:0.12182	eval-mlogloss:0.06114
[293]	train-mlogloss:0.12159	eval-mlogloss:0.06085
[294]	train-mlogloss:0.12148	eval-mlogloss:0.06082
[295]	train-mlogloss:0.12142	eval-mlogloss:0.06079
[296]	train-mlogloss:0.12142	eval-mlogloss:0.06081
[297]	train-mlogloss:0.12140	eval-mlogloss:0.06083
[298]	train-mlogloss:0.12134	eval-mlogloss:0.06074
[299]	train-mlogloss:0.12125	eval-mlogloss:0.06069

[I 2025-06-27 22:41:25,569] Trial 1 finished with value: 1.0 and parameters: {'lambda': 1.1304379092842615e-06, 'alpha': 1.8425401519596223e-06, 'eta': 0.029244898807741018, 'gamma': 1.6079247817381406e-05, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.4931319796720209, 'colsample_bytree': 0.9593176987688382}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.87384	eval-mlogloss:0.87801
[1]	train-mlogloss:0.76941	eval-mlogloss:0.79130

[I 2025-06-27 22:41:25,928] Trial 2 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.99089	eval-mlogloss:0.98657
[1]	train-mlogloss:0.93770	eval-mlogloss:0.93697
[2]	train-mlogloss:0.86140	eval-mlogloss:0.85700

[I 2025-06-27 22:41:25,940] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03386	eval-mlogloss:1.03071
[1]	train-mlogloss:0.99642	eval-mlogloss:0.99561

[I 2025-06-27 22:41:25,957] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.77485	eval-mlogloss:0.76334
[1]	train-mlogloss:0.57690	eval-mlogloss:0.55218

[I 2025-06-27 22:41:25,973] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.81619	eval-mlogloss:0.80160
[1]	train-mlogloss:0.68592	eval-mlogloss:0.69833

[I 2025-06-27 22:41:25,991] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02547	eval-mlogloss:1.02249
[1]	train-mlogloss:0.99204	eval-mlogloss:0.98353

[I 2025-06-27 22:41:26,004] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06061	eval-mlogloss:1.05855
[1]	train-mlogloss:1.04174	eval-mlogloss:1.03711
[2]	train-mlogloss:1.01788	eval-mlogloss:1.01603
[3]	train-mlogloss:0.97784	eval-mlogloss:0.97312
[4]	train-mlogloss:0.96212	eval-mlogloss:0.95678
[5]	train-mlogloss:0.93689	eval-mlogloss:0.93212
[6]	train-mlogloss:0.90105	eval-mlogloss:0.89348
[7]	train-mlogloss:0.86426	eval-mlogloss:0.85334
[8]	train-mlogloss:0.84767	eval-mlogloss:0.83804
[9]	train-mlogloss:0.81223	eval-mlogloss:0.80076
[10]	train-mlogloss:0.78721	eval-mlogloss:0.77419
[11]	train-mlogloss:0.77496	eval-mlogloss:0.76282
[12]	train-mlogloss:0.74937	eval-mlogloss:0.73379
[13]	train-mlogloss:0.72884	eval-mlogloss:0.71224
[14]	train-mlogloss:0.70140	eval-mlogloss:0.68245
[15]	train-mlogloss:0.68672	eval-mlogloss:0.66773
[16]	train-mlogloss:0.67428	eval-mlogloss:0.65226
[17]	train-mlogloss:0.65515	eval-mlogloss:0.63072
[18]	train-mlogloss:0.63591	eval-mlogloss:0.60958
[19]	train-mlogloss:0.63125	eval-mlogloss:0.60595
[20]	train-mlogloss:0.62639	eval-mlogloss:0.60114
[21]	train-mlogloss:0.61094	eval-mlogloss:0.58546
[22]	train-mlogloss:0.59107	eval-mlogloss:0.56232
[23]	train-mlogloss:0.57031	eval-mlogloss:0.54043
[24]	train-mlogloss:0.55433	eval-mlogloss:0.52274
[25]	train-mlogloss:0.53636	eval-mlogloss:0.50187
[26]	train-mlogloss:0.53285	eval-mlogloss:0.49837
[27]	train-mlogloss:0.51731	eval-mlogloss:0.48156
[28]	train-mlogloss:0.50889	eval-mlogloss:0.47348
[29]	train-mlogloss:0.50063	eval-mlogloss:0.46367
[30]	train-mlogloss:0.49425	eval-mlogloss:0.45767
[31]	train-mlogloss:0.48248	eval-mlogloss:0.44461
[32]	train-mlogloss:0.46885	eval-mlogloss:0.42994
[33]	train-mlogloss:0.46463	eval-mlogloss:0.42453
[34]	train-mlogloss:0.45655	eval-mlogloss:0.41516
[35]	train-mlogloss:0.44859	eval-mlogloss:0.40638
[36]	train-mlogloss:0.44205	eval-mlogloss:0.39896
[37]	train-mlogloss:0.43000	eval-mlogloss:0.38587
[38]	train-mlogloss:0.42516	eval-mlogloss:0.38090
[39]	train-mlogloss:0.41642	eval-mlogloss:0.37176
[40]	train-mlogloss:0.40982	eval-mlogloss:0.36518
[41]	train-mlogloss:0.40123	eval-mlogloss:0.35550
[42]	train-mlogloss:0.39443	eval-mlogloss:0.34777
[43]	train-mlogloss:0.38770	eval-mlogloss:0.34049
[44]	train-mlogloss:0.37984	eval-mlogloss:0.33183
[45]	train-mlogloss:0.37020	eval-mlogloss:0.32100
[46]	train-mlogloss:0.36810	eval-mlogloss:0.31888
[47]	train-mlogloss:0.36344	eval-mlogloss:0.31278
[48]	train-mlogloss:0.35924	eval-mlogloss:0.30874
[49]	train-mlogloss:0.35362	eval-mlogloss:0.30233
[50]	train-mlogloss:0.34798	eval-mlogloss:0.29536
[51]	train-mlogloss:0.34198	eval-mlogloss:0.28861
[52]	train-mlogloss:0.33830	eval-mlogloss:0.28447
[53]	train-mlogloss:0.33078	eval-mlogloss:0.27582
[54]	train-mlogloss:0.32873	eval-mlogloss:0.27398
[55]	train-mlogloss:0.32781	eval-mlogloss:0.27307
[56]	train-mlogloss:0.32503	eval-mlogloss:0.26968
[57]	train-mlogloss:0.32132	eval-mlogloss:0.26615
[58]	train-mlogloss:0.31576	eval-mlogloss:0.26022
[59]	train-mlogloss:0.30883	eval-mlogloss:0.25234
[60]	train-mlogloss:0.30752	eval-mlogloss:0.25077
[61]	train-mlogloss:0.30461	eval-mlogloss:0.24785
[62]	train-mlogloss:0.30058	eval-mlogloss:0.24369
[63]	train-mlogloss:0.30041	eval-mlogloss:0.24306
[64]	train-mlogloss:0.29825	eval-mlogloss:0.24068
[65]	train-mlogloss:0.29549	eval-mlogloss:0.23742
[66]	train-mlogloss:0.29119	eval-mlogloss:0.23284
[67]	train-mlogloss:0.28875	eval-mlogloss:0.23010
[68]	train-mlogloss:0.28641	eval-mlogloss:0.22716
[69]	train-mlogloss:0.28564	eval-mlogloss:0.22632
[70]	train-mlogloss:0.28511	eval-mlogloss:0.22554
[71]	train-mlogloss:0.28081	eval-mlogloss:0.22071
[72]	train-mlogloss:0.28080	eval-mlogloss:0.22072
[73]	train-mlogloss:0.28013	eval-mlogloss:0.22011
[74]	train-mlogloss:0.27771	eval-mlogloss:0.21766
[75]	train-mlogloss:0.27628	eval-mlogloss:0.21612
[76]	train-mlogloss:0.27555	eval-mlogloss:0.21524
[77]	train-mlogloss:0.27369	eval-mlogloss:0.21325
[78]	train-mlogloss:0.27370	eval-mlogloss:0.21331
[79]	train-mlogloss:0.27181	eval-mlogloss:0.21095
[80]	train-mlogloss:0.27062	eval-mlogloss:0.20970
[81]	train-mlogloss:0.27046	eval-mlogloss:0.20936
[82]	train-mlogloss:0.27011	eval-mlogloss:0.20909
[83]	train-mlogloss:0.27012	eval-mlogloss:0.20914
[84]	train-mlogloss:0.26832	eval-mlogloss:0.20728
[85]	train-mlogloss:0.26792	eval-mlogloss:0.20682
[86]	train-mlogloss:0.26593	eval-mlogloss:0.20401
[87]	train-mlogloss:0.26465	eval-mlogloss:0.20253
[88]	train-mlogloss:0.26329	eval-mlogloss:0.20121
[89]	train-mlogloss:0.26280	eval-mlogloss:0.20077
[90]	train-mlogloss:0.26268	eval-mlogloss:0.20080
[91]	train-mlogloss:0.26262	eval-mlogloss:0.20078
[92]	train-mlogloss:0.26226	eval-mlogloss:0.20021
[93]	train-mlogloss:0.26062	eval-mlogloss:0.19841
[94]	train-mlogloss:0.25871	eval-mlogloss:0.19617
[95]	train-mlogloss:0.25871	eval-mlogloss:0.19616
[96]	train-mlogloss:0.25755	eval-mlogloss:0.19462
[97]	train-mlogloss:0.25709	eval-mlogloss:0.19445
[98]	train-mlogloss:0.25561	eval-mlogloss:0.19244
[99]	train-mlogloss:0.25548	eval-mlogloss:0.19233
[100]	train-mlogloss:0.25548	eval-mlogloss:0.19231
[101]	train-mlogloss:0.25537	eval-mlogloss:0.19234
[102]	train-mlogloss:0.25528	eval-mlogloss:0.19232
[103]	train-mlogloss:0.25409	eval-mlogloss:0.19080
[104]	train-mlogloss:0.25284	eval-mlogloss:0.18927
[105]	train-mlogloss:0.25125	eval-mlogloss:0.18746
[106]	train-mlogloss:0.24969	eval-mlogloss:0.18551
[107]	train-mlogloss:0.24954	eval-mlogloss:0.18547
[108]	train-mlogloss:0.24945	eval-mlogloss:0.18544
[109]	train-mlogloss:0.24942	eval-mlogloss:0.18532
[110]	train-mlogloss:0.24934	eval-mlogloss:0.18527
[111]	train-mlogloss:0.24925	eval-mlogloss:0.18516
[112]	train-mlogloss:0.24764	eval-mlogloss:0.18303
[113]	train-mlogloss:0.24740	eval-mlogloss:0.18268
[114]	train-mlogloss:0.24628	eval-mlogloss:0.18106
[115]	train-mlogloss:0.24619	eval-mlogloss:0.18093
[116]	train-mlogloss:0.24619	eval-mlogloss:0.18095
[117]	train-mlogloss:0.24603	eval-mlogloss:0.18090
[118]	train-mlogloss:0.24599	eval-mlogloss:0.18080
[119]	train-mlogloss:0.24340	eval-mlogloss:0.17813
[120]	train-mlogloss:0.24339	eval-mlogloss:0.17813
[121]	train-mlogloss:0.24263	eval-mlogloss:0.17718
[122]	train-mlogloss:0.24261	eval-mlogloss:0.17711
[123]	train-mlogloss:0.24256	eval-mlogloss:0.17718
[124]	train-mlogloss:0.24147	eval-mlogloss:0.17565
[125]	train-mlogloss:0.24139	eval-mlogloss:0.17560
[126]	train-mlogloss:0.24052	eval-mlogloss:0.17428
[127]	train-mlogloss:0.24048	eval-mlogloss:0.17427
[128]	train-mlogloss:0.24044	eval-mlogloss:0.17418
[129]	train-mlogloss:0.24039	eval-mlogloss:0.17415
[130]	train-mlogloss:0.24040	eval-mlogloss:0.17409
[131]	train-mlogloss:0.24034	eval-mlogloss:0.17389
[132]	train-mlogloss:0.23997	eval-mlogloss:0.17351
[133]	train-mlogloss:0.23990	eval-mlogloss:0.17341
[134]	train-mlogloss:0.23976	eval-mlogloss:0.17329
[135]	train-mlogloss:0.23852	eval-mlogloss:0.17169
[136]	train-mlogloss:0.23839	eval-mlogloss:0.17162
[137]	train-mlogloss:0.23834	eval-mlogloss:0.17136
[138]	train-mlogloss:0.23829	eval-mlogloss:0.17132
[139]	train-mlogloss:0.23810	eval-mlogloss:0.17124
[140]	train-mlogloss:0.23798	eval-mlogloss:0.17109
[141]	train-mlogloss:0.23797	eval-mlogloss:0.17115
[142]	train-mlogloss:0.23797	eval-mlogloss:0.17111
[143]	train-mlogloss:0.23797	eval-mlogloss:0.17111
[144]	train-mlogloss:0.23794	eval-mlogloss:0.17100
[145]	train-mlogloss:0.23785	eval-mlogloss:0.17094
[146]	train-mlogloss:0.23783	eval-mlogloss:0.17093
[147]	train-mlogloss:0.23682	eval-mlogloss:0.16973
[148]	train-mlogloss:0.23676	eval-mlogloss:0.16973
[149]	train-mlogloss:0.23665	eval-mlogloss:0.16966
[150]	train-mlogloss:0.23664	eval-mlogloss:0.16966
[151]	train-mlogloss:0.23663	eval-mlogloss:0.16965
[152]	train-mlogloss:0.23664	eval-mlogloss:0.16964
[153]	train-mlogloss:0.23661	eval-mlogloss:0.16961
[154]	train-mlogloss:0.23532	eval-mlogloss:0.16784
[155]	train-mlogloss:0.23533	eval-mlogloss:0.16785
[156]	train-mlogloss:0.23535	eval-mlogloss:0.16780
[157]	train-mlogloss:0.23527	eval-mlogloss:0.16768
[158]	train-mlogloss:0.23520	eval-mlogloss:0.16761
[159]	train-mlogloss:0.23504	eval-mlogloss:0.16751
[160]	train-mlogloss:0.23486	eval-mlogloss:0.16735
[161]	train-mlogloss:0.23482	eval-mlogloss:0.16715
[162]	train-mlogloss:0.23481	eval-mlogloss:0.16717
[163]	train-mlogloss:0.23472	eval-mlogloss:0.16715
[164]	train-mlogloss:0.23465	eval-mlogloss:0.16705
[165]	train-mlogloss:0.23461	eval-mlogloss:0.16703
[166]	train-mlogloss:0.23447	eval-mlogloss:0.16683
[167]	train-mlogloss:0.23441	eval-mlogloss:0.16685
[168]	train-mlogloss:0.23441	eval-mlogloss:0.16685
[169]	train-mlogloss:0.23424	eval-mlogloss:0.16652
[170]	train-mlogloss:0.23418	eval-mlogloss:0.16663
[171]	train-mlogloss:0.23398	eval-mlogloss:0.16637
[172]	train-mlogloss:0.23391	eval-mlogloss:0.16622
[173]	train-mlogloss:0.23383	eval-mlogloss:0.16614
[174]	train-mlogloss:0.23382	eval-mlogloss:0.16620
[175]	train-mlogloss:0.23377	eval-mlogloss:0.16613
[176]	train-mlogloss:0.23361	eval-mlogloss:0.16598
[177]	train-mlogloss:0.23338	eval-mlogloss:0.16564
[178]	train-mlogloss:0.23336	eval-mlogloss:0.16565
[179]	train-mlogloss:0.23335	eval-mlogloss:0.16565
[180]	train-mlogloss:0.23330	eval-mlogloss:0.16556
[181]	train-mlogloss:0.23328	eval-mlogloss:0.16561
[182]	train-mlogloss:0.23321	eval-mlogloss:0.16531
[183]	train-mlogloss:0.23320	eval-mlogloss:0.16528
[184]	train-mlogloss:0.23317	eval-mlogloss:0.16532
[185]	train-mlogloss:0.23316	eval-mlogloss:0.16531
[186]	train-mlogloss:0.23312	eval-mlogloss:0.16525
[187]	train-mlogloss:0.23312	eval-mlogloss:0.16525
[188]	train-mlogloss:0.23308	eval-mlogloss:0.16508
[189]	train-mlogloss:0.23301	eval-mlogloss:0.16507
[190]	train-mlogloss:0.23296	eval-mlogloss:0.16509
[191]	train-mlogloss:0.23289	eval-mlogloss:0.16485
[192]	train-mlogloss:0.23288	eval-mlogloss:0.16489
[193]	train-mlogloss:0.23285	eval-mlogloss:0.16478
[194]	train-mlogloss:0.23272	eval-mlogloss:0.16460
[195]	train-mlogloss:0.23271	eval-mlogloss:0.16460
[196]	train-mlogloss:0.23268	eval-mlogloss:0.16453
[197]	train-mlogloss:0.23264	eval-mlogloss:0.16443
[198]	train-mlogloss:0.23256	eval-mlogloss:0.16452
[199]	train-mlogloss:0.23174	eval-mlogloss:0.16355
[200]	train-mlogloss:0.23174	eval-mlogloss:0.16353
[201]	train-mlogloss:0.23174	eval-mlogloss:0.16349
[202]	train-mlogloss:0.23174	eval-mlogloss:0.16349
[203]	train-mlogloss:0.23173	eval-mlogloss:0.16354
[204]	train-mlogloss:0.23164	eval-mlogloss:0.16346
[205]	train-mlogloss:0.23164	eval-mlogloss:0.16344
[206]	train-mlogloss:0.23160	eval-mlogloss:0.16344
[207]	train-mlogloss:0.23158	eval-mlogloss:0.16342
[208]	train-mlogloss:0.23157	eval-mlogloss:0.16347
[209]	train-mlogloss:0.23155	eval-mlogloss:0.16333
[210]	train-mlogloss:0.23148	eval-mlogloss:0.16321
[211]	train-mlogloss:0.23127	eval-mlogloss:0.16303
[212]	train-mlogloss:0.23127	eval-mlogloss:0.16297
[213]	train-mlogloss:0.23127	eval-mlogloss:0.16300
[214]	train-mlogloss:0.23126	eval-mlogloss:0.16298
[215]	train-mlogloss:0.23111	eval-mlogloss:0.16266
[216]	train-mlogloss:0.23098	eval-mlogloss:0.16245
[217]	train-mlogloss:0.23094	eval-mlogloss:0.16227
[218]	train-mlogloss:0.23007	eval-mlogloss:0.16107
[219]	train-mlogloss:0.23008	eval-mlogloss:0.16103
[220]	train-mlogloss:0.23007	eval-mlogloss:0.16102
[221]	train-mlogloss:0.23007	eval-mlogloss:0.16106
[222]	train-mlogloss:0.23005	eval-mlogloss:0.16107
[223]	train-mlogloss:0.23004	eval-mlogloss:0.16107
[224]	train-mlogloss:0.22992	eval-mlogloss:0.16087
[225]	train-mlogloss:0.22980	eval-mlogloss:0.16098
[226]	train-mlogloss:0.22975	eval-mlogloss:0.16102
[227]	train-mlogloss:0.22965	eval-mlogloss:0.16094
[228]	train-mlogloss:0.22964	eval-mlogloss:0.16095
[229]	train-mlogloss:0.22931	eval-mlogloss:0.16055
[230]	train-mlogloss:0.22924	eval-mlogloss:0.16057
[231]	train-mlogloss:0.22921	eval-mlogloss:0.16051
[232]	train-mlogloss:0.22919	eval-mlogloss:0.16052
[233]	train-mlogloss:0.22917	eval-mlogloss:0.16053
[234]	train-mlogloss:0.22917	eval-mlogloss:0.16049
[235]	train-mlogloss:0.22909	eval-mlogloss:0.16051
[236]	train-mlogloss:0.22910	eval-mlogloss:0.16046
[237]	train-mlogloss:0.22909	eval-mlogloss:0.16047
[238]	train-mlogloss:0.22895	eval-mlogloss:0.16039
[239]	train-mlogloss:0.22894	eval-mlogloss:0.16039
[240]	train-mlogloss:0.22894	eval-mlogloss:0.16044
[241]	train-mlogloss:0.22894	eval-mlogloss:0.16044
[242]	train-mlogloss:0.22894	eval-mlogloss:0.16045
[243]	train-mlogloss:0.22894	eval-mlogloss:0.16045
[244]	train-mlogloss:0.22893	eval-mlogloss:0.16045
[245]	train-mlogloss:0.22891	eval-mlogloss:0.16048
[246]	train-mlogloss:0.22891	eval-mlogloss:0.16040
[247]	train-mlogloss:0.22884	eval-mlogloss:0.16034
[248]	train-mlogloss:0.22884	eval-mlogloss:0.16037
[249]	train-mlogloss:0.22879	eval-mlogloss:0.16044
[250]	train-mlogloss:0.22873	eval-mlogloss:0.16015
[251]	train-mlogloss:0.22866	eval-mlogloss:0.16013
[252]	train-mlogloss:0.22863	eval-mlogloss:0.16008
[253]	train-mlogloss:0.22863	eval-mlogloss:0.16008
[254]	train-mlogloss:0.22863	eval-mlogloss:0.16011
[255]	train-mlogloss:0.22863	eval-mlogloss:0.16011
[256]	train-mlogloss:0.22854	eval-mlogloss:0.15994
[257]	train-mlogloss:0.22853	eval-mlogloss:0.15996
[258]	train-mlogloss:0.22741	eval-mlogloss:0.15873
[259]	train-mlogloss:0.22741	eval-mlogloss:0.15874
[260]	train-mlogloss:0.22739	eval-mlogloss:0.15866
[261]	train-mlogloss:0.22738	eval-mlogloss:0.15867
[262]	train-mlogloss:0.22733	eval-mlogloss:0.15863
[263]	train-mlogloss:0.22729	eval-mlogloss:0.15859
[264]	train-mlogloss:0.22727	eval-mlogloss:0.15855
[265]	train-mlogloss:0.22727	eval-mlogloss:0.15856
[266]	train-mlogloss:0.22722	eval-mlogloss:0.15857
[267]	train-mlogloss:0.22720	eval-mlogloss:0.15851
[268]	train-mlogloss:0.22700	eval-mlogloss:0.15832
[269]	train-mlogloss:0.22690	eval-mlogloss:0.15816
[270]	train-mlogloss:0.22689	eval-mlogloss:0.15811
[271]	train-mlogloss:0.22689	eval-mlogloss:0.15812
[272]	train-mlogloss:0.22689	eval-mlogloss:0.15812
[273]	train-mlogloss:0.22685	eval-mlogloss:0.15804
[274]	train-mlogloss:0.22682	eval-mlogloss:0.15808
[275]	train-mlogloss:0.22681	eval-mlogloss:0.15797
[276]	train-mlogloss:0.22680	eval-mlogloss:0.15789
[277]	train-mlogloss:0.22679	eval-mlogloss:0.15786
[278]	train-mlogloss:0.22679	eval-mlogloss:0.15786
[279]	train-mlogloss:0.22672	eval-mlogloss:0.15773
[280]	train-mlogloss:0.22569	eval-mlogloss:0.15622
[281]	train-mlogloss:0.22561	eval-mlogloss:0.15616
[282]	train-mlogloss:0.22559	eval-mlogloss:0.15613
[283]	train-mlogloss:0.22554	eval-mlogloss:0.15591
[284]	train-mlogloss:0.22552	eval-mlogloss:0.15588
[285]	train-mlogloss:0.22552	eval-mlogloss:0.15587
[286]	train-mlogloss:0.22549	eval-mlogloss:0.15589
[287]	train-mlogloss:0.22550	eval-mlogloss:0.15587
[288]	train-mlogloss:0.22549	eval-mlogloss:0.15587
[289]	train-mlogloss:0.22478	eval-mlogloss:0.15495
[290]	train-mlogloss:0.22472	eval-mlogloss:0.15491
[291]	train-mlogloss:0.22471	eval-mlogloss:0.15492
[292]	train-mlogloss:0.22470	eval-mlogloss:0.15489
[293]	train-mlogloss:0.22468	eval-mlogloss:0.15488
[294]	train-mlogloss:0.22468	eval-mlogloss:0.15489
[295]	train-mlogloss:0.22461	eval-mlogloss:0.15477
[296]	train-mlogloss:0.22460	eval-mlogloss:0.15485
[297]	train-mlogloss:0.22460	eval-mlogloss:0.15491
[298]	train-mlogloss:0.22459	eval-mlogloss:0.15489
[299]	train-mlogloss:0.22459	eval-mlogloss:0.15493

[I 2025-06-27 22:41:27,133] Trial 8 finished with value: 1.0 and parameters: {'lambda': 4.120802603581805e-06, 'alpha': 0.4788897113116029, 'eta': 0.04162035328581856, 'gamma': 3.1760142219052847e-06, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.6962811932933319, 'colsample_bytree': 0.4836162465807161}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.76086	eval-mlogloss:0.75360
[1]	train-mlogloss:0.55840	eval-mlogloss:0.53323

[I 2025-06-27 22:41:27,142] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90930	eval-mlogloss:0.90253
[1]	train-mlogloss:0.83296	eval-mlogloss:0.81490
[2]	train-mlogloss:0.71829	eval-mlogloss:0.69106

[I 2025-06-27 22:41:27,203] Trial 10 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90436	eval-mlogloss:0.90526
[1]	train-mlogloss:0.77235	eval-mlogloss:0.76184
[2]	train-mlogloss:0.65186	eval-mlogloss:0.63478

[I 2025-06-27 22:41:27,268] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96450	eval-mlogloss:0.96268
[1]	train-mlogloss:0.89124	eval-mlogloss:0.88836
[2]	train-mlogloss:0.79474	eval-mlogloss:0.78457

[I 2025-06-27 22:41:27,398] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88778	eval-mlogloss:0.87786
[1]	train-mlogloss:0.80540	eval-mlogloss:0.80443
[2]	train-mlogloss:0.71110	eval-mlogloss:0.71582

[I 2025-06-27 22:41:27,468] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95358	eval-mlogloss:0.95488
[1]	train-mlogloss:0.84939	eval-mlogloss:0.83778

[I 2025-06-27 22:41:27,529] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86864	eval-mlogloss:0.87105
[1]	train-mlogloss:0.73341	eval-mlogloss:0.71350

[I 2025-06-27 22:41:27,590] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87357	eval-mlogloss:0.87725
[1]	train-mlogloss:0.70627	eval-mlogloss:0.69857

[I 2025-06-27 22:41:27,676] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06861	eval-mlogloss:1.06702
[1]	train-mlogloss:1.05206	eval-mlogloss:1.04980
[2]	train-mlogloss:1.02563	eval-mlogloss:1.02195
[3]	train-mlogloss:0.99734	eval-mlogloss:0.99299
[4]	train-mlogloss:0.97115	eval-mlogloss:0.96586
[5]	train-mlogloss:0.94537	eval-mlogloss:0.93881
[6]	train-mlogloss:0.92138	eval-mlogloss:0.91315
[7]	train-mlogloss:0.89809	eval-mlogloss:0.88879
[8]	train-mlogloss:0.87568	eval-mlogloss:0.86534
[9]	train-mlogloss:0.85371	eval-mlogloss:0.84230
[10]	train-mlogloss:0.83474	eval-mlogloss:0.82289
[11]	train-mlogloss:0.81417	eval-mlogloss:0.80149
[12]	train-mlogloss:0.79704	eval-mlogloss:0.78315
[13]	train-mlogloss:0.77775	eval-mlogloss:0.76273
[14]	train-mlogloss:0.75958	eval-mlogloss:0.74297
[15]	train-mlogloss:0.74434	eval-mlogloss:0.72723
[16]	train-mlogloss:0.72911	eval-mlogloss:0.71177
[17]	train-mlogloss:0.71250	eval-mlogloss:0.69410
[18]	train-mlogloss:0.69892	eval-mlogloss:0.68067
[19]	train-mlogloss:0.68441	eval-mlogloss:0.66641
[20]	train-mlogloss:0.67134	eval-mlogloss:0.65343
[21]	train-mlogloss:0.65836	eval-mlogloss:0.63979
[22]	train-mlogloss:0.64361	eval-mlogloss:0.62375
[23]	train-mlogloss:0.62903	eval-mlogloss:0.60854
[24]	train-mlogloss:0.61518	eval-mlogloss:0.59373
[25]	train-mlogloss:0.60185	eval-mlogloss:0.57913
[26]	train-mlogloss:0.58982	eval-mlogloss:0.56650
[27]	train-mlogloss:0.57712	eval-mlogloss:0.55315
[28]	train-mlogloss:0.56482	eval-mlogloss:0.54038
[29]	train-mlogloss:0.55481	eval-mlogloss:0.52994
[30]	train-mlogloss:0.54699	eval-mlogloss:0.52345
[31]	train-mlogloss:0.53717	eval-mlogloss:0.51363
[32]	train-mlogloss:0.52599	eval-mlogloss:0.50169
[33]	train-mlogloss:0.51492	eval-mlogloss:0.48983
[34]	train-mlogloss:0.50619	eval-mlogloss:0.48158
[35]	train-mlogloss:0.49610	eval-mlogloss:0.47049
[36]	train-mlogloss:0.48701	eval-mlogloss:0.46103
[37]	train-mlogloss:0.47704	eval-mlogloss:0.45067
[38]	train-mlogloss:0.46787	eval-mlogloss:0.44123
[39]	train-mlogloss:0.45819	eval-mlogloss:0.43094
[40]	train-mlogloss:0.45088	eval-mlogloss:0.42408
[41]	train-mlogloss:0.44207	eval-mlogloss:0.41421
[42]	train-mlogloss:0.43342	eval-mlogloss:0.40480
[43]	train-mlogloss:0.42501	eval-mlogloss:0.39578
[44]	train-mlogloss:0.41869	eval-mlogloss:0.38922
[45]	train-mlogloss:0.41080	eval-mlogloss:0.38083
[46]	train-mlogloss:0.40246	eval-mlogloss:0.37284
[47]	train-mlogloss:0.39568	eval-mlogloss:0.36587
[48]	train-mlogloss:0.38809	eval-mlogloss:0.35813
[49]	train-mlogloss:0.38070	eval-mlogloss:0.35034
[50]	train-mlogloss:0.37383	eval-mlogloss:0.34271
[51]	train-mlogloss:0.36755	eval-mlogloss:0.33629
[52]	train-mlogloss:0.36322	eval-mlogloss:0.33199
[53]	train-mlogloss:0.35678	eval-mlogloss:0.32465
[54]	train-mlogloss:0.35192	eval-mlogloss:0.31987
[55]	train-mlogloss:0.34644	eval-mlogloss:0.31489
[56]	train-mlogloss:0.34136	eval-mlogloss:0.30944
[57]	train-mlogloss:0.33641	eval-mlogloss:0.30458
[58]	train-mlogloss:0.33204	eval-mlogloss:0.30026
[59]	train-mlogloss:0.32630	eval-mlogloss:0.29385
[60]	train-mlogloss:0.32054	eval-mlogloss:0.28791
[61]	train-mlogloss:0.31610	eval-mlogloss:0.28300
[62]	train-mlogloss:0.31067	eval-mlogloss:0.27727
[63]	train-mlogloss:0.30539	eval-mlogloss:0.27217
[64]	train-mlogloss:0.30048	eval-mlogloss:0.26708
[65]	train-mlogloss:0.29543	eval-mlogloss:0.26214
[66]	train-mlogloss:0.29033	eval-mlogloss:0.25670
[67]	train-mlogloss:0.28659	eval-mlogloss:0.25310
[68]	train-mlogloss:0.28293	eval-mlogloss:0.24959
[69]	train-mlogloss:0.27906	eval-mlogloss:0.24579
[70]	train-mlogloss:0.27525	eval-mlogloss:0.24177
[71]	train-mlogloss:0.27055	eval-mlogloss:0.23644
[72]	train-mlogloss:0.26787	eval-mlogloss:0.23364
[73]	train-mlogloss:0.26359	eval-mlogloss:0.22935
[74]	train-mlogloss:0.25960	eval-mlogloss:0.22547
[75]	train-mlogloss:0.25537	eval-mlogloss:0.22094
[76]	train-mlogloss:0.25306	eval-mlogloss:0.21866
[77]	train-mlogloss:0.24925	eval-mlogloss:0.21481
[78]	train-mlogloss:0.24616	eval-mlogloss:0.21135
[79]	train-mlogloss:0.24246	eval-mlogloss:0.20702
[80]	train-mlogloss:0.23962	eval-mlogloss:0.20355
[81]	train-mlogloss:0.23613	eval-mlogloss:0.19963
[82]	train-mlogloss:0.23313	eval-mlogloss:0.19656
[83]	train-mlogloss:0.22997	eval-mlogloss:0.19288
[84]	train-mlogloss:0.22661	eval-mlogloss:0.18932
[85]	train-mlogloss:0.22473	eval-mlogloss:0.18779
[86]	train-mlogloss:0.22182	eval-mlogloss:0.18427
[87]	train-mlogloss:0.21947	eval-mlogloss:0.18169
[88]	train-mlogloss:0.21674	eval-mlogloss:0.17853
[89]	train-mlogloss:0.21363	eval-mlogloss:0.17511
[90]	train-mlogloss:0.21093	eval-mlogloss:0.17239
[91]	train-mlogloss:0.20886	eval-mlogloss:0.16972
[92]	train-mlogloss:0.20670	eval-mlogloss:0.16727
[93]	train-mlogloss:0.20410	eval-mlogloss:0.16435
[94]	train-mlogloss:0.20131	eval-mlogloss:0.16171
[95]	train-mlogloss:0.19936	eval-mlogloss:0.15920
[96]	train-mlogloss:0.19698	eval-mlogloss:0.15614
[97]	train-mlogloss:0.19475	eval-mlogloss:0.15377
[98]	train-mlogloss:0.19265	eval-mlogloss:0.15151
[99]	train-mlogloss:0.19039	eval-mlogloss:0.14963
[100]	train-mlogloss:0.18864	eval-mlogloss:0.14768
[101]	train-mlogloss:0.18645	eval-mlogloss:0.14531
[102]	train-mlogloss:0.18430	eval-mlogloss:0.14304
[103]	train-mlogloss:0.18260	eval-mlogloss:0.14136
[104]	train-mlogloss:0.18100	eval-mlogloss:0.13950
[105]	train-mlogloss:0.17934	eval-mlogloss:0.13756
[106]	train-mlogloss:0.17706	eval-mlogloss:0.13550
[107]	train-mlogloss:0.17531	eval-mlogloss:0.13346
[108]	train-mlogloss:0.17355	eval-mlogloss:0.13132
[109]	train-mlogloss:0.17205	eval-mlogloss:0.12963
[110]	train-mlogloss:0.17027	eval-mlogloss:0.12735
[111]	train-mlogloss:0.16854	eval-mlogloss:0.12517
[112]	train-mlogloss:0.16722	eval-mlogloss:0.12364
[113]	train-mlogloss:0.16603	eval-mlogloss:0.12237
[114]	train-mlogloss:0.16439	eval-mlogloss:0.12050
[115]	train-mlogloss:0.16295	eval-mlogloss:0.11860
[116]	train-mlogloss:0.16197	eval-mlogloss:0.11779
[117]	train-mlogloss:0.16047	eval-mlogloss:0.11575
[118]	train-mlogloss:0.15917	eval-mlogloss:0.11427
[119]	train-mlogloss:0.15793	eval-mlogloss:0.11303
[120]	train-mlogloss:0.15678	eval-mlogloss:0.11175
[121]	train-mlogloss:0.15525	eval-mlogloss:0.10988
[122]	train-mlogloss:0.15415	eval-mlogloss:0.10864
[123]	train-mlogloss:0.15339	eval-mlogloss:0.10799
[124]	train-mlogloss:0.15253	eval-mlogloss:0.10706
[125]	train-mlogloss:0.15161	eval-mlogloss:0.10586
[126]	train-mlogloss:0.15114	eval-mlogloss:0.10553
[127]	train-mlogloss:0.15022	eval-mlogloss:0.10431
[128]	train-mlogloss:0.14952	eval-mlogloss:0.10320

[I 2025-06-27 22:41:28,120] Trial 17 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:0.91646	eval-mlogloss:0.91399
[1]	train-mlogloss:0.77852	eval-mlogloss:0.77122

[I 2025-06-27 22:41:28,186] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.99470	eval-mlogloss:0.99096
[1]	train-mlogloss:0.94662	eval-mlogloss:0.93746
[2]	train-mlogloss:0.87021	eval-mlogloss:0.85558

[I 2025-06-27 22:41:28,249] Trial 19 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.92378	eval-mlogloss:0.91366
[1]	train-mlogloss:0.85186	eval-mlogloss:0.83679

[I 2025-06-27 22:41:28,312] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08655	eval-mlogloss:1.08590
[1]	train-mlogloss:1.08022	eval-mlogloss:1.07881
[2]	train-mlogloss:1.07213	eval-mlogloss:1.07154
[3]	train-mlogloss:1.05829	eval-mlogloss:1.05674
[4]	train-mlogloss:1.05279	eval-mlogloss:1.05075
[5]	train-mlogloss:1.04347	eval-mlogloss:1.04094
[6]	train-mlogloss:1.03011	eval-mlogloss:1.02671
[7]	train-mlogloss:1.01579	eval-mlogloss:1.01120
[8]	train-mlogloss:1.00884	eval-mlogloss:1.00481
[9]	train-mlogloss:0.99430	eval-mlogloss:0.98963
[10]	train-mlogloss:0.98340	eval-mlogloss:0.97878
[11]	train-mlogloss:0.97786	eval-mlogloss:0.97399
[12]	train-mlogloss:0.96624	eval-mlogloss:0.96097
[13]	train-mlogloss:0.95654	eval-mlogloss:0.95104
[14]	train-mlogloss:0.94351	eval-mlogloss:0.93705
[15]	train-mlogloss:0.93598	eval-mlogloss:0.92966
[16]	train-mlogloss:0.92945	eval-mlogloss:0.92157
[17]	train-mlogloss:0.91926	eval-mlogloss:0.91084
[18]	train-mlogloss:0.90901	eval-mlogloss:0.90006
[19]	train-mlogloss:0.90583	eval-mlogloss:0.89688
[20]	train-mlogloss:0.90252	eval-mlogloss:0.89379
[21]	train-mlogloss:0.89369	eval-mlogloss:0.88499
[22]	train-mlogloss:0.88135	eval-mlogloss:0.87156
[23]	train-mlogloss:0.86973	eval-mlogloss:0.85924
[24]	train-mlogloss:0.85975	eval-mlogloss:0.84870
[25]	train-mlogloss:0.84806	eval-mlogloss:0.83640
[26]	train-mlogloss:0.84548	eval-mlogloss:0.83393
[27]	train-mlogloss:0.83554	eval-mlogloss:0.82337
[28]	train-mlogloss:0.82943	eval-mlogloss:0.81779
[29]	train-mlogloss:0.82271	eval-mlogloss:0.81079
[30]	train-mlogloss:0.81780	eval-mlogloss:0.80588
[31]	train-mlogloss:0.80956	eval-mlogloss:0.79726
[32]	train-mlogloss:0.79917	eval-mlogloss:0.78659
[33]	train-mlogloss:0.79511	eval-mlogloss:0.78215
[34]	train-mlogloss:0.78895	eval-mlogloss:0.77535
[35]	train-mlogloss:0.78197	eval-mlogloss:0.76821
[36]	train-mlogloss:0.77587	eval-mlogloss:0.76202
[37]	train-mlogloss:0.76602	eval-mlogloss:0.75149
[38]	train-mlogloss:0.75948	eval-mlogloss:0.74475
[39]	train-mlogloss:0.75242	eval-mlogloss:0.73726
[40]	train-mlogloss:0.74726	eval-mlogloss:0.73267
[41]	train-mlogloss:0.74033	eval-mlogloss:0.72491
[42]	train-mlogloss:0.73310	eval-mlogloss:0.71697
[43]	train-mlogloss:0.72598	eval-mlogloss:0.70971
[44]	train-mlogloss:0.71900	eval-mlogloss:0.70244
[45]	train-mlogloss:0.70986	eval-mlogloss:0.69277
[46]	train-mlogloss:0.70703	eval-mlogloss:0.69017
[47]	train-mlogloss:0.70108	eval-mlogloss:0.68402
[48]	train-mlogloss:0.69526	eval-mlogloss:0.67811
[49]	train-mlogloss:0.68942	eval-mlogloss:0.67194
[50]	train-mlogloss:0.68209	eval-mlogloss:0.66373
[51]	train-mlogloss:0.67574	eval-mlogloss:0.65697
[52]	train-mlogloss:0.67142	eval-mlogloss:0.65234
[53]	train-mlogloss:0.66349	eval-mlogloss:0.64380
[54]	train-mlogloss:0.65894	eval-mlogloss:0.63906
[55]	train-mlogloss:0.65725	eval-mlogloss:0.63789
[56]	train-mlogloss:0.65273	eval-mlogloss:0.63293
[57]	train-mlogloss:0.64761	eval-mlogloss:0.62770
[58]	train-mlogloss:0.64192	eval-mlogloss:0.62203
[59]	train-mlogloss:0.63417	eval-mlogloss:0.61343
[60]	train-mlogloss:0.62865	eval-mlogloss:0.60735
[61]	train-mlogloss:0.62538	eval-mlogloss:0.60405
[62]	train-mlogloss:0.61878	eval-mlogloss:0.59700
[63]	train-mlogloss:0.61558	eval-mlogloss:0.59385
[64]	train-mlogloss:0.61062	eval-mlogloss:0.58875
[65]	train-mlogloss:0.60702	eval-mlogloss:0.58472
[66]	train-mlogloss:0.60006	eval-mlogloss:0.57728
[67]	train-mlogloss:0.59645	eval-mlogloss:0.57316
[68]	train-mlogloss:0.59144	eval-mlogloss:0.56752
[69]	train-mlogloss:0.58840	eval-mlogloss:0.56474
[70]	train-mlogloss:0.58603	eval-mlogloss:0.56212
[71]	train-mlogloss:0.57985	eval-mlogloss:0.55492
[72]	train-mlogloss:0.57856	eval-mlogloss:0.55394
[73]	train-mlogloss:0.57481	eval-mlogloss:0.55023
[74]	train-mlogloss:0.56874	eval-mlogloss:0.54354
[75]	train-mlogloss:0.56509	eval-mlogloss:0.53988
[76]	train-mlogloss:0.56315	eval-mlogloss:0.53800
[77]	train-mlogloss:0.55846	eval-mlogloss:0.53303
[78]	train-mlogloss:0.55394	eval-mlogloss:0.52832
[79]	train-mlogloss:0.54947	eval-mlogloss:0.52326
[80]	train-mlogloss:0.54769	eval-mlogloss:0.52141
[81]	train-mlogloss:0.54517	eval-mlogloss:0.51896
[82]	train-mlogloss:0.54155	eval-mlogloss:0.51527
[83]	train-mlogloss:0.53878	eval-mlogloss:0.51253
[84]	train-mlogloss:0.53458	eval-mlogloss:0.50783
[85]	train-mlogloss:0.53115	eval-mlogloss:0.50438
[86]	train-mlogloss:0.52827	eval-mlogloss:0.50097
[87]	train-mlogloss:0.52397	eval-mlogloss:0.49627
[88]	train-mlogloss:0.52101	eval-mlogloss:0.49314
[89]	train-mlogloss:0.51712	eval-mlogloss:0.48920
[90]	train-mlogloss:0.51502	eval-mlogloss:0.48691
[91]	train-mlogloss:0.51291	eval-mlogloss:0.48455
[92]	train-mlogloss:0.51081	eval-mlogloss:0.48198
[93]	train-mlogloss:0.50795	eval-mlogloss:0.47897
[94]	train-mlogloss:0.50260	eval-mlogloss:0.47326
[95]	train-mlogloss:0.49897	eval-mlogloss:0.46889
[96]	train-mlogloss:0.49528	eval-mlogloss:0.46487
[97]	train-mlogloss:0.49282	eval-mlogloss:0.46215
[98]	train-mlogloss:0.48891	eval-mlogloss:0.45775
[99]	train-mlogloss:0.48802	eval-mlogloss:0.45705
[100]	train-mlogloss:0.48612	eval-mlogloss:0.45526
[101]	train-mlogloss:0.48403	eval-mlogloss:0.45313
[102]	train-mlogloss:0.48057	eval-mlogloss:0.44950
[103]	train-mlogloss:0.47696	eval-mlogloss:0.44562
[104]	train-mlogloss:0.47336	eval-mlogloss:0.44193
[105]	train-mlogloss:0.46976	eval-mlogloss:0.43775
[106]	train-mlogloss:0.46597	eval-mlogloss:0.43350
[107]	train-mlogloss:0.46416	eval-mlogloss:0.43142
[108]	train-mlogloss:0.46091	eval-mlogloss:0.42817
[109]	train-mlogloss:0.45813	eval-mlogloss:0.42531
[110]	train-mlogloss:0.45616	eval-mlogloss:0.42311
[111]	train-mlogloss:0.45182	eval-mlogloss:0.41800
[112]	train-mlogloss:0.44898	eval-mlogloss:0.41474
[113]	train-mlogloss:0.44633	eval-mlogloss:0.41149
[114]	train-mlogloss:0.44322	eval-mlogloss:0.40774
[115]	train-mlogloss:0.43990	eval-mlogloss:0.40374
[116]	train-mlogloss:0.43847	eval-mlogloss:0.40207
[117]	train-mlogloss:0.43514	eval-mlogloss:0.39824
[118]	train-mlogloss:0.43458	eval-mlogloss:0.39773
[119]	train-mlogloss:0.43193	eval-mlogloss:0.39480
[120]	train-mlogloss:0.42908	eval-mlogloss:0.39143
[121]	train-mlogloss:0.42537	eval-mlogloss:0.38705
[122]	train-mlogloss:0.42338	eval-mlogloss:0.38486
[123]	train-mlogloss:0.42114	eval-mlogloss:0.38237
[124]	train-mlogloss:0.41861	eval-mlogloss:0.37977
[125]	train-mlogloss:0.41700	eval-mlogloss:0.37808
[126]	train-mlogloss:0.41436	eval-mlogloss:0.37522
[127]	train-mlogloss:0.41202	eval-mlogloss:0.37291
[128]	train-mlogloss:0.40880	eval-mlogloss:0.36924
[129]	train-mlogloss:0.40614	eval-mlogloss:0.36610
[130]	train-mlogloss:0.40297	eval-mlogloss:0.36258
[131]	train-mlogloss:0.40075	eval-mlogloss:0.35989
[132]	train-mlogloss:0.39803	eval-mlogloss:0.35706
[133]	train-mlogloss:0.39717	eval-mlogloss:0.35617
[134]	train-mlogloss:0.39455	eval-mlogloss:0.35326
[135]	train-mlogloss:0.39247	eval-mlogloss:0.35112
[136]	train-mlogloss:0.38998	eval-mlogloss:0.34837
[137]	train-mlogloss:0.38741	eval-mlogloss:0.34541
[138]	train-mlogloss:0.38463	eval-mlogloss:0.34236
[139]	train-mlogloss:0.38327	eval-mlogloss:0.34092
[140]	train-mlogloss:0.38136	eval-mlogloss:0.33861
[141]	train-mlogloss:0.37884	eval-mlogloss:0.33591
[142]	train-mlogloss:0.37714	eval-mlogloss:0.33402
[143]	train-mlogloss:0.37516	eval-mlogloss:0.33189
[144]	train-mlogloss:0.37270	eval-mlogloss:0.32914
[145]	train-mlogloss:0.37115	eval-mlogloss:0.32735
[146]	train-mlogloss:0.36842	eval-mlogloss:0.32441
[147]	train-mlogloss:0.36598	eval-mlogloss:0.32166
[148]	train-mlogloss:0.36427	eval-mlogloss:0.32000
[149]	train-mlogloss:0.36214	eval-mlogloss:0.31772
[150]	train-mlogloss:0.36125	eval-mlogloss:0.31687
[151]	train-mlogloss:0.35992	eval-mlogloss:0.31544
[152]	train-mlogloss:0.35733	eval-mlogloss:0.31245
[153]	train-mlogloss:0.35598	eval-mlogloss:0.31094
[154]	train-mlogloss:0.35355	eval-mlogloss:0.30818
[155]	train-mlogloss:0.35186	eval-mlogloss:0.30622
[156]	train-mlogloss:0.35041	eval-mlogloss:0.30459
[157]	train-mlogloss:0.34826	eval-mlogloss:0.30213
[158]	train-mlogloss:0.34538	eval-mlogloss:0.29881
[159]	train-mlogloss:0.34422	eval-mlogloss:0.29779
[160]	train-mlogloss:0.34387	eval-mlogloss:0.29752
[161]	train-mlogloss:0.34325	eval-mlogloss:0.29669
[162]	train-mlogloss:0.34197	eval-mlogloss:0.29521
[163]	train-mlogloss:0.34163	eval-mlogloss:0.29506
[164]	train-mlogloss:0.33952	eval-mlogloss:0.29260
[165]	train-mlogloss:0.33885	eval-mlogloss:0.29203
[166]	train-mlogloss:0.33709	eval-mlogloss:0.29006
[167]	train-mlogloss:0.33520	eval-mlogloss:0.28791
[168]	train-mlogloss:0.33385	eval-mlogloss:0.28648
[169]	train-mlogloss:0.33186	eval-mlogloss:0.28417
[170]	train-mlogloss:0.33008	eval-mlogloss:0.28225
[171]	train-mlogloss:0.32944	eval-mlogloss:0.28151
[172]	train-mlogloss:0.32759	eval-mlogloss:0.27938
[173]	train-mlogloss:0.32615	eval-mlogloss:0.27781
[174]	train-mlogloss:0.32553	eval-mlogloss:0.27708
[175]	train-mlogloss:0.32408	eval-mlogloss:0.27548
[176]	train-mlogloss:0.32303	eval-mlogloss:0.27446
[177]	train-mlogloss:0.32233	eval-mlogloss:0.27361
[178]	train-mlogloss:0.32094	eval-mlogloss:0.27202
[179]	train-mlogloss:0.31909	eval-mlogloss:0.27006
[180]	train-mlogloss:0.31689	eval-mlogloss:0.26764
[181]	train-mlogloss:0.31631	eval-mlogloss:0.26701
[182]	train-mlogloss:0.31493	eval-mlogloss:0.26534
[183]	train-mlogloss:0.31383	eval-mlogloss:0.26431
[184]	train-mlogloss:0.31234	eval-mlogloss:0.26271
[185]	train-mlogloss:0.31179	eval-mlogloss:0.26220
[186]	train-mlogloss:0.31122	eval-mlogloss:0.26169
[187]	train-mlogloss:0.31011	eval-mlogloss:0.26044
[188]	train-mlogloss:0.30936	eval-mlogloss:0.25955
[189]	train-mlogloss:0.30843	eval-mlogloss:0.25840
[190]	train-mlogloss:0.30716	eval-mlogloss:0.25702
[191]	train-mlogloss:0.30707	eval-mlogloss:0.25684
[192]	train-mlogloss:0.30617	eval-mlogloss:0.25607
[193]	train-mlogloss:0.30507	eval-mlogloss:0.25478
[194]	train-mlogloss:0.30440	eval-mlogloss:0.25419
[195]	train-mlogloss:0.30306	eval-mlogloss:0.25265
[196]	train-mlogloss:0.30153	eval-mlogloss:0.25086
[197]	train-mlogloss:0.30072	eval-mlogloss:0.25002
[198]	train-mlogloss:0.30021	eval-mlogloss:0.24945
[199]	train-mlogloss:0.29948	eval-mlogloss:0.24852
[200]	train-mlogloss:0.29872	eval-mlogloss:0.24774
[201]	train-mlogloss:0.29834	eval-mlogloss:0.24728
[202]	train-mlogloss:0.29732	eval-mlogloss:0.24627
[203]	train-mlogloss:0.29590	eval-mlogloss:0.24463
[204]	train-mlogloss:0.29508	eval-mlogloss:0.24372
[205]	train-mlogloss:0.29410	eval-mlogloss:0.24268
[206]	train-mlogloss:0.29327	eval-mlogloss:0.24173
[207]	train-mlogloss:0.29239	eval-mlogloss:0.24077
[208]	train-mlogloss:0.29221	eval-mlogloss:0.24067
[209]	train-mlogloss:0.29115	eval-mlogloss:0.23958
[210]	train-mlogloss:0.29112	eval-mlogloss:0.23953
[211]	train-mlogloss:0.29067	eval-mlogloss:0.23901
[212]	train-mlogloss:0.28988	eval-mlogloss:0.23798
[213]	train-mlogloss:0.28928	eval-mlogloss:0.23735
[214]	train-mlogloss:0.28847	eval-mlogloss:0.23635
[215]	train-mlogloss:0.28768	eval-mlogloss:0.23540
[216]	train-mlogloss:0.28736	eval-mlogloss:0.23508
[217]	train-mlogloss:0.28660	eval-mlogloss:0.23402
[218]	train-mlogloss:0.28592	eval-mlogloss:0.23332
[219]	train-mlogloss:0.28497	eval-mlogloss:0.23227
[220]	train-mlogloss:0.28426	eval-mlogloss:0.23153
[221]	train-mlogloss:0.28371	eval-mlogloss:0.23088
[222]	train-mlogloss:0.28223	eval-mlogloss:0.22937
[223]	train-mlogloss:0.28207	eval-mlogloss:0.22915
[224]	train-mlogloss:0.28123	eval-mlogloss:0.22820
[225]	train-mlogloss:0.28094	eval-mlogloss:0.22796
[226]	train-mlogloss:0.28092	eval-mlogloss:0.22797
[227]	train-mlogloss:0.27948	eval-mlogloss:0.22642
[228]	train-mlogloss:0.27913	eval-mlogloss:0.22602
[229]	train-mlogloss:0.27894	eval-mlogloss:0.22579
[230]	train-mlogloss:0.27874	eval-mlogloss:0.22562
[231]	train-mlogloss:0.27817	eval-mlogloss:0.22496
[232]	train-mlogloss:0.27812	eval-mlogloss:0.22501
[233]	train-mlogloss:0.27739	eval-mlogloss:0.22425
[234]	train-mlogloss:0.27596	eval-mlogloss:0.22264
[235]	train-mlogloss:0.27553	eval-mlogloss:0.22233
[236]	train-mlogloss:0.27477	eval-mlogloss:0.22155
[237]	train-mlogloss:0.27417	eval-mlogloss:0.22093
[238]	train-mlogloss:0.27411	eval-mlogloss:0.22091
[239]	train-mlogloss:0.27407	eval-mlogloss:0.22090
[240]	train-mlogloss:0.27390	eval-mlogloss:0.22063
[241]	train-mlogloss:0.27387	eval-mlogloss:0.22065
[242]	train-mlogloss:0.27382	eval-mlogloss:0.22068
[243]	train-mlogloss:0.27375	eval-mlogloss:0.22067
[244]	train-mlogloss:0.27318	eval-mlogloss:0.21991
[245]	train-mlogloss:0.27258	eval-mlogloss:0.21928
[246]	train-mlogloss:0.27256	eval-mlogloss:0.21918
[247]	train-mlogloss:0.27199	eval-mlogloss:0.21857
[248]	train-mlogloss:0.27119	eval-mlogloss:0.21774
[249]	train-mlogloss:0.27037	eval-mlogloss:0.21677
[250]	train-mlogloss:0.27025	eval-mlogloss:0.21645
[251]	train-mlogloss:0.27022	eval-mlogloss:0.21645
[252]	train-mlogloss:0.26936	eval-mlogloss:0.21551
[253]	train-mlogloss:0.26932	eval-mlogloss:0.21542
[254]	train-mlogloss:0.26813	eval-mlogloss:0.21402
[255]	train-mlogloss:0.26808	eval-mlogloss:0.21403
[256]	train-mlogloss:0.26747	eval-mlogloss:0.21323
[257]	train-mlogloss:0.26677	eval-mlogloss:0.21239
[258]	train-mlogloss:0.26611	eval-mlogloss:0.21154
[259]	train-mlogloss:0.26550	eval-mlogloss:0.21087
[260]	train-mlogloss:0.26548	eval-mlogloss:0.21077
[261]	train-mlogloss:0.26490	eval-mlogloss:0.21014
[262]	train-mlogloss:0.26486	eval-mlogloss:0.21016
[263]	train-mlogloss:0.26422	eval-mlogloss:0.20948
[264]	train-mlogloss:0.26370	eval-mlogloss:0.20887
[265]	train-mlogloss:0.26355	eval-mlogloss:0.20875
[266]	train-mlogloss:0.26353	eval-mlogloss:0.20875
[267]	train-mlogloss:0.26339	eval-mlogloss:0.20854
[268]	train-mlogloss:0.26319	eval-mlogloss:0.20828
[269]	train-mlogloss:0.26269	eval-mlogloss:0.20771
[270]	train-mlogloss:0.26214	eval-mlogloss:0.20704
[271]	train-mlogloss:0.26152	eval-mlogloss:0.20626
[272]	train-mlogloss:0.26101	eval-mlogloss:0.20560
[273]	train-mlogloss:0.26054	eval-mlogloss:0.20507
[274]	train-mlogloss:0.25995	eval-mlogloss:0.20449
[275]	train-mlogloss:0.25945	eval-mlogloss:0.20379
[276]	train-mlogloss:0.25940	eval-mlogloss:0.20376
[277]	train-mlogloss:0.25881	eval-mlogloss:0.20318
[278]	train-mlogloss:0.25878	eval-mlogloss:0.20314
[279]	train-mlogloss:0.25818	eval-mlogloss:0.20238
[280]	train-mlogloss:0.25762	eval-mlogloss:0.20154
[281]	train-mlogloss:0.25753	eval-mlogloss:0.20143
[282]	train-mlogloss:0.25751	eval-mlogloss:0.20139
[283]	train-mlogloss:0.25699	eval-mlogloss:0.20063
[284]	train-mlogloss:0.25696	eval-mlogloss:0.20059
[285]	train-mlogloss:0.25686	eval-mlogloss:0.20050
[286]	train-mlogloss:0.25683	eval-mlogloss:0.20049
[287]	train-mlogloss:0.25680	eval-mlogloss:0.20044
[288]	train-mlogloss:0.25631	eval-mlogloss:0.19985
[289]	train-mlogloss:0.25585	eval-mlogloss:0.19921
[290]	train-mlogloss:0.25532	eval-mlogloss:0.19855
[291]	train-mlogloss:0.25480	eval-mlogloss:0.19794
[292]	train-mlogloss:0.25478	eval-mlogloss:0.19791
[293]	train-mlogloss:0.25422	eval-mlogloss:0.19732
[294]	train-mlogloss:0.25411	eval-mlogloss:0.19723
[295]	train-mlogloss:0.25344	eval-mlogloss:0.19653
[296]	train-mlogloss:0.25331	eval-mlogloss:0.19659
[297]	train-mlogloss:0.25329	eval-mlogloss:0.19661
[298]	train-mlogloss:0.25323	eval-mlogloss:0.19660
[299]	train-mlogloss:0.25320	eval-mlogloss:0.19666

[I 2025-06-27 22:41:29,302] Trial 21 finished with value: 1.0 and parameters: {'lambda': 6.633568239917303e-06, 'alpha': 0.2042242744663753, 'eta': 0.012888431980068112, 'gamma': 2.1548891015956027e-06, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.6864991573886426, 'colsample_bytree': 0.46019868221093985}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04807	eval-mlogloss:1.04534
[1]	train-mlogloss:1.02503	eval-mlogloss:1.01988
[2]	train-mlogloss:0.98451	eval-mlogloss:0.97658
[3]	train-mlogloss:0.94055	eval-mlogloss:0.92934
[4]	train-mlogloss:0.90111	eval-mlogloss:0.88883
[5]	train-mlogloss:0.86164	eval-mlogloss:0.84677
[6]	train-mlogloss:0.82609	eval-mlogloss:0.80888
[7]	train-mlogloss:0.79360	eval-mlogloss:0.77254
[8]	train-mlogloss:0.76262	eval-mlogloss:0.73908

[I 2025-06-27 22:41:29,382] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99555	eval-mlogloss:0.99183
[1]	train-mlogloss:0.95026	eval-mlogloss:0.94149
[2]	train-mlogloss:0.89292	eval-mlogloss:0.88152

[I 2025-06-27 22:41:29,514] Trial 23 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05359	eval-mlogloss:1.05152
[1]	train-mlogloss:1.02794	eval-mlogloss:1.02603
[2]	train-mlogloss:0.99045	eval-mlogloss:0.98798
[3]	train-mlogloss:0.95129	eval-mlogloss:0.94772
[4]	train-mlogloss:0.91470	eval-mlogloss:0.91002
[5]	train-mlogloss:0.87971	eval-mlogloss:0.87302
[6]	train-mlogloss:0.84730	eval-mlogloss:0.83834
[7]	train-mlogloss:0.81609	eval-mlogloss:0.80573

[I 2025-06-27 22:41:29,595] Trial 24 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04223	eval-mlogloss:1.03897
[1]	train-mlogloss:1.01419	eval-mlogloss:1.00870

[I 2025-06-27 22:41:29,667] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94843	eval-mlogloss:0.93931
[1]	train-mlogloss:0.87942	eval-mlogloss:0.86847
[2]	train-mlogloss:0.77898	eval-mlogloss:0.76292

[I 2025-06-27 22:41:29,755] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86158	eval-mlogloss:0.85332
[1]	train-mlogloss:0.77079	eval-mlogloss:0.73474
[2]	train-mlogloss:0.69600	eval-mlogloss:0.65875

[I 2025-06-27 22:41:29,824] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88913	eval-mlogloss:0.88396
[1]	train-mlogloss:0.79979	eval-mlogloss:0.79495

[I 2025-06-27 22:41:29,893] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90320	eval-mlogloss:0.89427
[1]	train-mlogloss:0.81412	eval-mlogloss:0.79679

[I 2025-06-27 22:41:29,961] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88164	eval-mlogloss:0.86937
[1]	train-mlogloss:0.80476	eval-mlogloss:0.80173
[2]	train-mlogloss:0.71226	eval-mlogloss:0.71073

[I 2025-06-27 22:41:30,027] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08779	eval-mlogloss:1.08720
[1]	train-mlogloss:1.08204	eval-mlogloss:1.08073
[2]	train-mlogloss:1.07473	eval-mlogloss:1.07418
[3]	train-mlogloss:1.06231	eval-mlogloss:1.06092
[4]	train-mlogloss:1.05706	eval-mlogloss:1.05547
[5]	train-mlogloss:1.04863	eval-mlogloss:1.04659
[6]	train-mlogloss:1.03654	eval-mlogloss:1.03371
[7]	train-mlogloss:1.02353	eval-mlogloss:1.01962
[8]	train-mlogloss:1.01722	eval-mlogloss:1.01381
[9]	train-mlogloss:1.00401	eval-mlogloss:1.00002
[10]	train-mlogloss:0.99405	eval-mlogloss:0.99011
[11]	train-mlogloss:0.98880	eval-mlogloss:0.98529
[12]	train-mlogloss:0.97814	eval-mlogloss:0.97380
[13]	train-mlogloss:0.96927	eval-mlogloss:0.96472
[14]	train-mlogloss:0.95733	eval-mlogloss:0.95191
[15]	train-mlogloss:0.95040	eval-mlogloss:0.94512
[16]	train-mlogloss:0.94439	eval-mlogloss:0.93769
[17]	train-mlogloss:0.93502	eval-mlogloss:0.92794
[18]	train-mlogloss:0.92562	eval-mlogloss:0.91808
[19]	train-mlogloss:0.92267	eval-mlogloss:0.91515
[20]	train-mlogloss:0.91962	eval-mlogloss:0.91232
[21]	train-mlogloss:0.91145	eval-mlogloss:0.90417
[22]	train-mlogloss:0.90005	eval-mlogloss:0.89178
[23]	train-mlogloss:0.88929	eval-mlogloss:0.88039
[24]	train-mlogloss:0.88004	eval-mlogloss:0.87061
[25]	train-mlogloss:0.86921	eval-mlogloss:0.85911
[26]	train-mlogloss:0.86676	eval-mlogloss:0.85676
[27]	train-mlogloss:0.85751	eval-mlogloss:0.84686
[28]	train-mlogloss:0.85178	eval-mlogloss:0.84164
[29]	train-mlogloss:0.84548	eval-mlogloss:0.83508
[30]	train-mlogloss:0.84087	eval-mlogloss:0.83048
[31]	train-mlogloss:0.83315	eval-mlogloss:0.82242
[32]	train-mlogloss:0.82345	eval-mlogloss:0.81245
[33]	train-mlogloss:0.81960	eval-mlogloss:0.80826
[34]	train-mlogloss:0.81378	eval-mlogloss:0.80186
[35]	train-mlogloss:0.80721	eval-mlogloss:0.79512
[36]	train-mlogloss:0.80150	eval-mlogloss:0.78935
[37]	train-mlogloss:0.79225	eval-mlogloss:0.77948
[38]	train-mlogloss:0.78606	eval-mlogloss:0.77313
[39]	train-mlogloss:0.77939	eval-mlogloss:0.76605
[40]	train-mlogloss:0.77449	eval-mlogloss:0.76159
[41]	train-mlogloss:0.76796	eval-mlogloss:0.75430
[42]	train-mlogloss:0.76111	eval-mlogloss:0.74679
[43]	train-mlogloss:0.75435	eval-mlogloss:0.73991
[44]	train-mlogloss:0.74772	eval-mlogloss:0.73301
[45]	train-mlogloss:0.73905	eval-mlogloss:0.72385
[46]	train-mlogloss:0.73631	eval-mlogloss:0.72136
[47]	train-mlogloss:0.73077	eval-mlogloss:0.71535
[48]	train-mlogloss:0.72519	eval-mlogloss:0.70969
[49]	train-mlogloss:0.71957	eval-mlogloss:0.70381
[50]	train-mlogloss:0.71256	eval-mlogloss:0.69598
[51]	train-mlogloss:0.70649	eval-mlogloss:0.68953
[52]	train-mlogloss:0.70239	eval-mlogloss:0.68509
[53]	train-mlogloss:0.69481	eval-mlogloss:0.67693
[54]	train-mlogloss:0.69042	eval-mlogloss:0.67231
[55]	train-mlogloss:0.68871	eval-mlogloss:0.67113
[56]	train-mlogloss:0.68433	eval-mlogloss:0.66636
[57]	train-mlogloss:0.67937	eval-mlogloss:0.66129
[58]	train-mlogloss:0.67390	eval-mlogloss:0.65586
[59]	train-mlogloss:0.66646	eval-mlogloss:0.64761
[60]	train-mlogloss:0.66083	eval-mlogloss:0.64157
[61]	train-mlogloss:0.65755	eval-mlogloss:0.63827
[62]	train-mlogloss:0.65120	eval-mlogloss:0.63149
[63]	train-mlogloss:0.64806	eval-mlogloss:0.62842
[64]	train-mlogloss:0.64325	eval-mlogloss:0.62348
[65]	train-mlogloss:0.63956	eval-mlogloss:0.61961
[66]	train-mlogloss:0.63283	eval-mlogloss:0.61242
[67]	train-mlogloss:0.62936	eval-mlogloss:0.60851
[68]	train-mlogloss:0.62450	eval-mlogloss:0.60306
[69]	train-mlogloss:0.62155	eval-mlogloss:0.60035
[70]	train-mlogloss:0.61937	eval-mlogloss:0.59807
[71]	train-mlogloss:0.61337	eval-mlogloss:0.59109
[72]	train-mlogloss:0.61207	eval-mlogloss:0.59011
[73]	train-mlogloss:0.60838	eval-mlogloss:0.58636
[74]	train-mlogloss:0.60228	eval-mlogloss:0.57978
[75]	train-mlogloss:0.59864	eval-mlogloss:0.57612
[76]	train-mlogloss:0.59670	eval-mlogloss:0.57424
[77]	train-mlogloss:0.59212	eval-mlogloss:0.56939
[78]	train-mlogloss:0.58771	eval-mlogloss:0.56480
[79]	train-mlogloss:0.58333	eval-mlogloss:0.55984
[80]	train-mlogloss:0.58154	eval-mlogloss:0.55801
[81]	train-mlogloss:0.57905	eval-mlogloss:0.55559
[82]	train-mlogloss:0.57533	eval-mlogloss:0.55175
[83]	train-mlogloss:0.57250	eval-mlogloss:0.54885
[84]	train-mlogloss:0.56838	eval-mlogloss:0.54425
[85]	train-mlogloss:0.56498	eval-mlogloss:0.54083
[86]	train-mlogloss:0.56198	eval-mlogloss:0.53766
[87]	train-mlogloss:0.55773	eval-mlogloss:0.53304
[88]	train-mlogloss:0.55451	eval-mlogloss:0.52983
[89]	train-mlogloss:0.55064	eval-mlogloss:0.52591
[90]	train-mlogloss:0.54839	eval-mlogloss:0.52353
[91]	train-mlogloss:0.54628	eval-mlogloss:0.52115
[92]	train-mlogloss:0.54413	eval-mlogloss:0.51877
[93]	train-mlogloss:0.54130	eval-mlogloss:0.51576
[94]	train-mlogloss:0.53589	eval-mlogloss:0.51010
[95]	train-mlogloss:0.53179	eval-mlogloss:0.50551
[96]	train-mlogloss:0.52809	eval-mlogloss:0.50150
[97]	train-mlogloss:0.52563	eval-mlogloss:0.49891
[98]	train-mlogloss:0.52175	eval-mlogloss:0.49464
[99]	train-mlogloss:0.52077	eval-mlogloss:0.49379
[100]	train-mlogloss:0.51885	eval-mlogloss:0.49197
[101]	train-mlogloss:0.51677	eval-mlogloss:0.48984
[102]	train-mlogloss:0.51325	eval-mlogloss:0.48620
[103]	train-mlogloss:0.50966	eval-mlogloss:0.48234
[104]	train-mlogloss:0.50608	eval-mlogloss:0.47867
[105]	train-mlogloss:0.50252	eval-mlogloss:0.47454
[106]	train-mlogloss:0.49859	eval-mlogloss:0.47010
[107]	train-mlogloss:0.49673	eval-mlogloss:0.46800
[108]	train-mlogloss:0.49360	eval-mlogloss:0.46470
[109]	train-mlogloss:0.49083	eval-mlogloss:0.46176
[110]	train-mlogloss:0.48859	eval-mlogloss:0.45923
[111]	train-mlogloss:0.48427	eval-mlogloss:0.45415
[112]	train-mlogloss:0.48138	eval-mlogloss:0.45096
[113]	train-mlogloss:0.47869	eval-mlogloss:0.44768
[114]	train-mlogloss:0.47551	eval-mlogloss:0.44393
[115]	train-mlogloss:0.47230	eval-mlogloss:0.44008
[116]	train-mlogloss:0.47076	eval-mlogloss:0.43847
[117]	train-mlogloss:0.46731	eval-mlogloss:0.43461
[118]	train-mlogloss:0.46673	eval-mlogloss:0.43407
[119]	train-mlogloss:0.46407	eval-mlogloss:0.43115
[120]	train-mlogloss:0.46119	eval-mlogloss:0.42774
[121]	train-mlogloss:0.45741	eval-mlogloss:0.42329
[122]	train-mlogloss:0.45538	eval-mlogloss:0.42106
[123]	train-mlogloss:0.45305	eval-mlogloss:0.41854
[124]	train-mlogloss:0.45049	eval-mlogloss:0.41591
[125]	train-mlogloss:0.44887	eval-mlogloss:0.41420
[126]	train-mlogloss:0.44604	eval-mlogloss:0.41130
[127]	train-mlogloss:0.44363	eval-mlogloss:0.40877
[128]	train-mlogloss:0.44025	eval-mlogloss:0.40489
[129]	train-mlogloss:0.43738	eval-mlogloss:0.40168
[130]	train-mlogloss:0.43391	eval-mlogloss:0.39793
[131]	train-mlogloss:0.43163	eval-mlogloss:0.39534
[132]	train-mlogloss:0.42879	eval-mlogloss:0.39224
[133]	train-mlogloss:0.42785	eval-mlogloss:0.39135
[134]	train-mlogloss:0.42519	eval-mlogloss:0.38830
[135]	train-mlogloss:0.42289	eval-mlogloss:0.38586
[136]	train-mlogloss:0.42035	eval-mlogloss:0.38297
[137]	train-mlogloss:0.41765	eval-mlogloss:0.37996
[138]	train-mlogloss:0.41465	eval-mlogloss:0.37653
[139]	train-mlogloss:0.41320	eval-mlogloss:0.37506
[140]	train-mlogloss:0.41125	eval-mlogloss:0.37272
[141]	train-mlogloss:0.40869	eval-mlogloss:0.36998
[142]	train-mlogloss:0.40696	eval-mlogloss:0.36804
[143]	train-mlogloss:0.40491	eval-mlogloss:0.36573
[144]	train-mlogloss:0.40242	eval-mlogloss:0.36294
[145]	train-mlogloss:0.40067	eval-mlogloss:0.36107
[146]	train-mlogloss:0.39785	eval-mlogloss:0.35792
[147]	train-mlogloss:0.39537	eval-mlogloss:0.35512
[148]	train-mlogloss:0.39314	eval-mlogloss:0.35280
[149]	train-mlogloss:0.39095	eval-mlogloss:0.35026
[150]	train-mlogloss:0.38972	eval-mlogloss:0.34891
[151]	train-mlogloss:0.38815	eval-mlogloss:0.34719
[152]	train-mlogloss:0.38552	eval-mlogloss:0.34417
[153]	train-mlogloss:0.38408	eval-mlogloss:0.34256
[154]	train-mlogloss:0.38156	eval-mlogloss:0.33974
[155]	train-mlogloss:0.37969	eval-mlogloss:0.33755
[156]	train-mlogloss:0.37820	eval-mlogloss:0.33587
[157]	train-mlogloss:0.37597	eval-mlogloss:0.33335
[158]	train-mlogloss:0.37297	eval-mlogloss:0.33002
[159]	train-mlogloss:0.37180	eval-mlogloss:0.32898
[160]	train-mlogloss:0.37133	eval-mlogloss:0.32852
[161]	train-mlogloss:0.37065	eval-mlogloss:0.32772
[162]	train-mlogloss:0.36928	eval-mlogloss:0.32614
[163]	train-mlogloss:0.36888	eval-mlogloss:0.32583
[164]	train-mlogloss:0.36626	eval-mlogloss:0.32278
[165]	train-mlogloss:0.36557	eval-mlogloss:0.32218
[166]	train-mlogloss:0.36373	eval-mlogloss:0.32017
[167]	train-mlogloss:0.36181	eval-mlogloss:0.31797
[168]	train-mlogloss:0.36036	eval-mlogloss:0.31648
[169]	train-mlogloss:0.35833	eval-mlogloss:0.31412
[170]	train-mlogloss:0.35633	eval-mlogloss:0.31200
[171]	train-mlogloss:0.35536	eval-mlogloss:0.31094
[172]	train-mlogloss:0.35342	eval-mlogloss:0.30868
[173]	train-mlogloss:0.35193	eval-mlogloss:0.30704
[174]	train-mlogloss:0.35069	eval-mlogloss:0.30548
[175]	train-mlogloss:0.34921	eval-mlogloss:0.30386
[176]	train-mlogloss:0.34814	eval-mlogloss:0.30281
[177]	train-mlogloss:0.34741	eval-mlogloss:0.30191
[178]	train-mlogloss:0.34572	eval-mlogloss:0.29997
[179]	train-mlogloss:0.34379	eval-mlogloss:0.29785
[180]	train-mlogloss:0.34148	eval-mlogloss:0.29525
[181]	train-mlogloss:0.34009	eval-mlogloss:0.29385
[182]	train-mlogloss:0.33868	eval-mlogloss:0.29235
[183]	train-mlogloss:0.33755	eval-mlogloss:0.29129
[184]	train-mlogloss:0.33594	eval-mlogloss:0.28970
[185]	train-mlogloss:0.33503	eval-mlogloss:0.28872
[186]	train-mlogloss:0.33447	eval-mlogloss:0.28821
[187]	train-mlogloss:0.33331	eval-mlogloss:0.28694
[188]	train-mlogloss:0.33237	eval-mlogloss:0.28589
[189]	train-mlogloss:0.33119	eval-mlogloss:0.28453
[190]	train-mlogloss:0.32988	eval-mlogloss:0.28311
[191]	train-mlogloss:0.32938	eval-mlogloss:0.28242
[192]	train-mlogloss:0.32837	eval-mlogloss:0.28147
[193]	train-mlogloss:0.32725	eval-mlogloss:0.28016
[194]	train-mlogloss:0.32653	eval-mlogloss:0.27952
[195]	train-mlogloss:0.32501	eval-mlogloss:0.27775
[196]	train-mlogloss:0.32344	eval-mlogloss:0.27593
[197]	train-mlogloss:0.32256	eval-mlogloss:0.27510
[198]	train-mlogloss:0.32163	eval-mlogloss:0.27410
[199]	train-mlogloss:0.32085	eval-mlogloss:0.27312
[200]	train-mlogloss:0.31991	eval-mlogloss:0.27225
[201]	train-mlogloss:0.31951	eval-mlogloss:0.27179
[202]	train-mlogloss:0.31846	eval-mlogloss:0.27074
[203]	train-mlogloss:0.31684	eval-mlogloss:0.26887
[204]	train-mlogloss:0.31585	eval-mlogloss:0.26774
[205]	train-mlogloss:0.31383	eval-mlogloss:0.26556
[206]	train-mlogloss:0.31237	eval-mlogloss:0.26391
[207]	train-mlogloss:0.31147	eval-mlogloss:0.26292
[208]	train-mlogloss:0.31127	eval-mlogloss:0.26280
[209]	train-mlogloss:0.31019	eval-mlogloss:0.26169
[210]	train-mlogloss:0.31016	eval-mlogloss:0.26166
[211]	train-mlogloss:0.30897	eval-mlogloss:0.26036
[212]	train-mlogloss:0.30776	eval-mlogloss:0.25890
[213]	train-mlogloss:0.30704	eval-mlogloss:0.25804
[214]	train-mlogloss:0.30617	eval-mlogloss:0.25698
[215]	train-mlogloss:0.30518	eval-mlogloss:0.25587
[216]	train-mlogloss:0.30421	eval-mlogloss:0.25481
[217]	train-mlogloss:0.30275	eval-mlogloss:0.25303
[218]	train-mlogloss:0.30172	eval-mlogloss:0.25184
[219]	train-mlogloss:0.30073	eval-mlogloss:0.25076
[220]	train-mlogloss:0.29950	eval-mlogloss:0.24931
[221]	train-mlogloss:0.29895	eval-mlogloss:0.24865
[222]	train-mlogloss:0.29747	eval-mlogloss:0.24715
[223]	train-mlogloss:0.29728	eval-mlogloss:0.24691
[224]	train-mlogloss:0.29603	eval-mlogloss:0.24546
[225]	train-mlogloss:0.29573	eval-mlogloss:0.24520
[226]	train-mlogloss:0.29497	eval-mlogloss:0.24448
[227]	train-mlogloss:0.29352	eval-mlogloss:0.24293
[228]	train-mlogloss:0.29311	eval-mlogloss:0.24240
[229]	train-mlogloss:0.29274	eval-mlogloss:0.24201
[230]	train-mlogloss:0.29177	eval-mlogloss:0.24099
[231]	train-mlogloss:0.29106	eval-mlogloss:0.24018
[232]	train-mlogloss:0.29103	eval-mlogloss:0.24024
[233]	train-mlogloss:0.29027	eval-mlogloss:0.23947
[234]	train-mlogloss:0.28878	eval-mlogloss:0.23776
[235]	train-mlogloss:0.28836	eval-mlogloss:0.23745
[236]	train-mlogloss:0.28756	eval-mlogloss:0.23664
[237]	train-mlogloss:0.28639	eval-mlogloss:0.23540
[238]	train-mlogloss:0.28624	eval-mlogloss:0.23523
[239]	train-mlogloss:0.28586	eval-mlogloss:0.23489
[240]	train-mlogloss:0.28569	eval-mlogloss:0.23462
[241]	train-mlogloss:0.28565	eval-mlogloss:0.23460
[242]	train-mlogloss:0.28556	eval-mlogloss:0.23459
[243]	train-mlogloss:0.28518	eval-mlogloss:0.23427
[244]	train-mlogloss:0.28461	eval-mlogloss:0.23350
[245]	train-mlogloss:0.28398	eval-mlogloss:0.23285
[246]	train-mlogloss:0.28396	eval-mlogloss:0.23275
[247]	train-mlogloss:0.28337	eval-mlogloss:0.23209
[248]	train-mlogloss:0.28256	eval-mlogloss:0.23126
[249]	train-mlogloss:0.28173	eval-mlogloss:0.23028
[250]	train-mlogloss:0.28158	eval-mlogloss:0.23001
[251]	train-mlogloss:0.28143	eval-mlogloss:0.22979
[252]	train-mlogloss:0.28060	eval-mlogloss:0.22886
[253]	train-mlogloss:0.28055	eval-mlogloss:0.22875
[254]	train-mlogloss:0.27939	eval-mlogloss:0.22739
[255]	train-mlogloss:0.27934	eval-mlogloss:0.22736
[256]	train-mlogloss:0.27874	eval-mlogloss:0.22656
[257]	train-mlogloss:0.27795	eval-mlogloss:0.22561
[258]	train-mlogloss:0.27729	eval-mlogloss:0.22475
[259]	train-mlogloss:0.27667	eval-mlogloss:0.22407
[260]	train-mlogloss:0.27665	eval-mlogloss:0.22397
[261]	train-mlogloss:0.27545	eval-mlogloss:0.22262
[262]	train-mlogloss:0.27541	eval-mlogloss:0.22262
[263]	train-mlogloss:0.27475	eval-mlogloss:0.22193
[264]	train-mlogloss:0.27421	eval-mlogloss:0.22131
[265]	train-mlogloss:0.27405	eval-mlogloss:0.22118
[266]	train-mlogloss:0.27356	eval-mlogloss:0.22058
[267]	train-mlogloss:0.27337	eval-mlogloss:0.22032
[268]	train-mlogloss:0.27253	eval-mlogloss:0.21938
[269]	train-mlogloss:0.27194	eval-mlogloss:0.21873
[270]	train-mlogloss:0.27138	eval-mlogloss:0.21807
[271]	train-mlogloss:0.27076	eval-mlogloss:0.21729
[272]	train-mlogloss:0.27015	eval-mlogloss:0.21664
[273]	train-mlogloss:0.26965	eval-mlogloss:0.21601
[274]	train-mlogloss:0.26875	eval-mlogloss:0.21509
[275]	train-mlogloss:0.26814	eval-mlogloss:0.21439
[276]	train-mlogloss:0.26810	eval-mlogloss:0.21436
[277]	train-mlogloss:0.26744	eval-mlogloss:0.21367
[278]	train-mlogloss:0.26677	eval-mlogloss:0.21299
[279]	train-mlogloss:0.26618	eval-mlogloss:0.21235
[280]	train-mlogloss:0.26561	eval-mlogloss:0.21153
[281]	train-mlogloss:0.26552	eval-mlogloss:0.21142
[282]	train-mlogloss:0.26550	eval-mlogloss:0.21138
[283]	train-mlogloss:0.26499	eval-mlogloss:0.21063
[284]	train-mlogloss:0.26497	eval-mlogloss:0.21060
[285]	train-mlogloss:0.26487	eval-mlogloss:0.21051
[286]	train-mlogloss:0.26484	eval-mlogloss:0.21050
[287]	train-mlogloss:0.26481	eval-mlogloss:0.21045
[288]	train-mlogloss:0.26431	eval-mlogloss:0.20988
[289]	train-mlogloss:0.26333	eval-mlogloss:0.20869
[290]	train-mlogloss:0.26282	eval-mlogloss:0.20805
[291]	train-mlogloss:0.26222	eval-mlogloss:0.20730
[292]	train-mlogloss:0.26218	eval-mlogloss:0.20730
[293]	train-mlogloss:0.26164	eval-mlogloss:0.20672
[294]	train-mlogloss:0.26149	eval-mlogloss:0.20655
[295]	train-mlogloss:0.26029	eval-mlogloss:0.20519
[296]	train-mlogloss:0.26018	eval-mlogloss:0.20525
[297]	train-mlogloss:0.25973	eval-mlogloss:0.20471
[298]	train-mlogloss:0.25926	eval-mlogloss:0.20418
[299]	train-mlogloss:0.25922	eval-mlogloss:0.20424

[I 2025-06-27 22:41:31,099] Trial 31 finished with value: 1.0 and parameters: {'lambda': 8.19220810756799e-06, 'alpha': 0.16287581243333202, 'eta': 0.011524470753248743, 'gamma': 2.619789579401964e-06, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.692294248530961, 'colsample_bytree': 0.4666751797740617}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08180	eval-mlogloss:1.08088
[1]	train-mlogloss:1.07400	eval-mlogloss:1.07266
[2]	train-mlogloss:1.05943	eval-mlogloss:1.05710
[3]	train-mlogloss:1.04301	eval-mlogloss:1.04002
[4]	train-mlogloss:1.02768	eval-mlogloss:1.02447
[5]	train-mlogloss:1.01197	eval-mlogloss:1.00776
[6]	train-mlogloss:0.99710	eval-mlogloss:0.99200
[7]	train-mlogloss:0.98325	eval-mlogloss:0.97694
[8]	train-mlogloss:0.96895	eval-mlogloss:0.96186

[I 2025-06-27 22:41:31,185] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06602	eval-mlogloss:1.06448
[1]	train-mlogloss:1.04811	eval-mlogloss:1.04475
[2]	train-mlogloss:1.02650	eval-mlogloss:1.02542
[3]	train-mlogloss:0.99093	eval-mlogloss:0.98739
[4]	train-mlogloss:0.97535	eval-mlogloss:0.97032
[5]	train-mlogloss:0.95158	eval-mlogloss:0.94542
[6]	train-mlogloss:0.91866	eval-mlogloss:0.90925
[7]	train-mlogloss:0.88546	eval-mlogloss:0.87319
[8]	train-mlogloss:0.87014	eval-mlogloss:0.85937

[I 2025-06-27 22:41:31,274] Trial 33 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04200	eval-mlogloss:1.03894
[1]	train-mlogloss:1.01473	eval-mlogloss:1.01007
[2]	train-mlogloss:0.97936	eval-mlogloss:0.97844

[I 2025-06-27 22:41:31,343] Trial 34 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00565	eval-mlogloss:1.00048
[1]	train-mlogloss:0.95906	eval-mlogloss:0.95240
[2]	train-mlogloss:0.88794	eval-mlogloss:0.87833

[I 2025-06-27 22:41:31,411] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96911	eval-mlogloss:0.96628
[1]	train-mlogloss:0.86210	eval-mlogloss:0.85118

[I 2025-06-27 22:41:31,478] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06120	eval-mlogloss:1.05981
[1]	train-mlogloss:1.03718	eval-mlogloss:1.03953
[2]	train-mlogloss:1.00458	eval-mlogloss:1.00515
[3]	train-mlogloss:0.97000	eval-mlogloss:0.96918
[4]	train-mlogloss:0.93880	eval-mlogloss:0.93682
[5]	train-mlogloss:0.90831	eval-mlogloss:0.90466
[6]	train-mlogloss:0.88018	eval-mlogloss:0.87499
[7]	train-mlogloss:0.85286	eval-mlogloss:0.84605

[I 2025-06-27 22:41:31,562] Trial 37 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05320	eval-mlogloss:1.05371
[1]	train-mlogloss:1.02958	eval-mlogloss:1.03100
[2]	train-mlogloss:1.00002	eval-mlogloss:1.00651
[3]	train-mlogloss:0.95407	eval-mlogloss:0.95652
[4]	train-mlogloss:0.93405	eval-mlogloss:0.94102
[5]	train-mlogloss:0.90463	eval-mlogloss:0.91467
[6]	train-mlogloss:0.86482	eval-mlogloss:0.87091
[7]	train-mlogloss:0.82433	eval-mlogloss:0.82632

[I 2025-06-27 22:41:31,643] Trial 38 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.01105	eval-mlogloss:1.00928
[1]	train-mlogloss:0.93402	eval-mlogloss:0.92603
[2]	train-mlogloss:0.86491	eval-mlogloss:0.85541

[I 2025-06-27 22:41:31,712] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07126	eval-mlogloss:1.07041
[1]	train-mlogloss:1.05917	eval-mlogloss:1.05698
[2]	train-mlogloss:1.03748	eval-mlogloss:1.03541
[3]	train-mlogloss:1.01292	eval-mlogloss:1.00951
[4]	train-mlogloss:0.98864	eval-mlogloss:0.98485
[5]	train-mlogloss:0.96363	eval-mlogloss:0.95829
[6]	train-mlogloss:0.94536	eval-mlogloss:0.93862
[7]	train-mlogloss:0.92958	eval-mlogloss:0.92235
[8]	train-mlogloss:0.90849	eval-mlogloss:0.89943

[I 2025-06-27 22:41:31,793] Trial 40 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08914	eval-mlogloss:1.08863
[1]	train-mlogloss:1.08411	eval-mlogloss:1.08298
[2]	train-mlogloss:1.07773	eval-mlogloss:1.07726
[3]	train-mlogloss:1.06683	eval-mlogloss:1.06562
[4]	train-mlogloss:1.06247	eval-mlogloss:1.06099
[5]	train-mlogloss:1.05503	eval-mlogloss:1.05317
[6]	train-mlogloss:1.04437	eval-mlogloss:1.04179
[7]	train-mlogloss:1.03290	eval-mlogloss:1.02937
[8]	train-mlogloss:1.02727	eval-mlogloss:1.02417
[9]	train-mlogloss:1.01554	eval-mlogloss:1.01193
[10]	train-mlogloss:1.00671	eval-mlogloss:1.00315
[11]	train-mlogloss:1.00204	eval-mlogloss:0.99886
[12]	train-mlogloss:0.99251	eval-mlogloss:0.98862
[13]	train-mlogloss:0.98458	eval-mlogloss:0.98050
[14]	train-mlogloss:0.97391	eval-mlogloss:0.96906
[15]	train-mlogloss:0.96770	eval-mlogloss:0.96297
[16]	train-mlogloss:0.96232	eval-mlogloss:0.95641
[17]	train-mlogloss:0.95389	eval-mlogloss:0.94765
[18]	train-mlogloss:0.94542	eval-mlogloss:0.93877
[19]	train-mlogloss:0.94275	eval-mlogloss:0.93611
[20]	train-mlogloss:0.93997	eval-mlogloss:0.93352
[21]	train-mlogloss:0.93259	eval-mlogloss:0.92617
[22]	train-mlogloss:0.92228	eval-mlogloss:0.91498
[23]	train-mlogloss:0.91255	eval-mlogloss:0.90467
[24]	train-mlogloss:0.90413	eval-mlogloss:0.89579
[25]	train-mlogloss:0.89427	eval-mlogloss:0.88543
[26]	train-mlogloss:0.89204	eval-mlogloss:0.88328
[27]	train-mlogloss:0.88362	eval-mlogloss:0.87436
[28]	train-mlogloss:0.87841	eval-mlogloss:0.86961
[29]	train-mlogloss:0.87266	eval-mlogloss:0.86362
[30]	train-mlogloss:0.86843	eval-mlogloss:0.85940
[31]	train-mlogloss:0.86135	eval-mlogloss:0.85201
[32]	train-mlogloss:0.85245	eval-mlogloss:0.84287
[33]	train-mlogloss:0.84890	eval-mlogloss:0.83901
[34]	train-mlogloss:0.84358	eval-mlogloss:0.83315
[35]	train-mlogloss:0.83754	eval-mlogloss:0.82697
[36]	train-mlogloss:0.83222	eval-mlogloss:0.82160
[37]	train-mlogloss:0.82368	eval-mlogloss:0.81249
[38]	train-mlogloss:0.81795	eval-mlogloss:0.80663
[39]	train-mlogloss:0.81178	eval-mlogloss:0.80007
[40]	train-mlogloss:0.80724	eval-mlogloss:0.79603
[41]	train-mlogloss:0.80118	eval-mlogloss:0.78926
[42]	train-mlogloss:0.79484	eval-mlogloss:0.78234
[43]	train-mlogloss:0.78857	eval-mlogloss:0.77597
[44]	train-mlogloss:0.78237	eval-mlogloss:0.76953
[45]	train-mlogloss:0.77431	eval-mlogloss:0.76100
[46]	train-mlogloss:0.77173	eval-mlogloss:0.75866
[47]	train-mlogloss:0.76654	eval-mlogloss:0.75305
[48]	train-mlogloss:0.76121	eval-mlogloss:0.74782
[49]	train-mlogloss:0.75599	eval-mlogloss:0.74234
[50]	train-mlogloss:0.74943	eval-mlogloss:0.73503
[51]	train-mlogloss:0.74372	eval-mlogloss:0.72893
[52]	train-mlogloss:0.73981	eval-mlogloss:0.72476
[53]	train-mlogloss:0.73269	eval-mlogloss:0.71710
[54]	train-mlogloss:0.72857	eval-mlogloss:0.71283
[55]	train-mlogloss:0.72687	eval-mlogloss:0.71180
[56]	train-mlogloss:0.72274	eval-mlogloss:0.70730
[57]	train-mlogloss:0.71806	eval-mlogloss:0.70252
[58]	train-mlogloss:0.71288	eval-mlogloss:0.69738
[59]	train-mlogloss:0.70586	eval-mlogloss:0.68962
[60]	train-mlogloss:0.70054	eval-mlogloss:0.68391
[61]	train-mlogloss:0.69744	eval-mlogloss:0.68075
[62]	train-mlogloss:0.69143	eval-mlogloss:0.67435
[63]	train-mlogloss:0.68842	eval-mlogloss:0.67139
[64]	train-mlogloss:0.68384	eval-mlogloss:0.66670
[65]	train-mlogloss:0.68027	eval-mlogloss:0.66294
[66]	train-mlogloss:0.67386	eval-mlogloss:0.65610
[67]	train-mlogloss:0.67055	eval-mlogloss:0.65227
[68]	train-mlogloss:0.66584	eval-mlogloss:0.64698
[69]	train-mlogloss:0.66302	eval-mlogloss:0.64440
[70]	train-mlogloss:0.66090	eval-mlogloss:0.64219
[71]	train-mlogloss:0.65518	eval-mlogloss:0.63555
[72]	train-mlogloss:0.65391	eval-mlogloss:0.63458
[73]	train-mlogloss:0.65039	eval-mlogloss:0.63100
[74]	train-mlogloss:0.64443	eval-mlogloss:0.62465
[75]	train-mlogloss:0.64093	eval-mlogloss:0.62119
[76]	train-mlogloss:0.63900	eval-mlogloss:0.61928
[77]	train-mlogloss:0.63460	eval-mlogloss:0.61460
[78]	train-mlogloss:0.63036	eval-mlogloss:0.61021
[79]	train-mlogloss:0.62612	eval-mlogloss:0.60544
[80]	train-mlogloss:0.62438	eval-mlogloss:0.60362
[81]	train-mlogloss:0.62192	eval-mlogloss:0.60120
[82]	train-mlogloss:0.61817	eval-mlogloss:0.59742
[83]	train-mlogloss:0.61544	eval-mlogloss:0.59463
[84]	train-mlogloss:0.61144	eval-mlogloss:0.59017
[85]	train-mlogloss:0.60815	eval-mlogloss:0.58685
[86]	train-mlogloss:0.60518	eval-mlogloss:0.58364
[87]	train-mlogloss:0.60100	eval-mlogloss:0.57927
[88]	train-mlogloss:0.59788	eval-mlogloss:0.57617
[89]	train-mlogloss:0.59413	eval-mlogloss:0.57243
[90]	train-mlogloss:0.59193	eval-mlogloss:0.57011
[91]	train-mlogloss:0.58932	eval-mlogloss:0.56744
[92]	train-mlogloss:0.58721	eval-mlogloss:0.56513
[93]	train-mlogloss:0.58445	eval-mlogloss:0.56221
[94]	train-mlogloss:0.57910	eval-mlogloss:0.55666
[95]	train-mlogloss:0.57512	eval-mlogloss:0.55223
[96]	train-mlogloss:0.57150	eval-mlogloss:0.54830
[97]	train-mlogloss:0.56871	eval-mlogloss:0.54561
[98]	train-mlogloss:0.56495	eval-mlogloss:0.54141
[99]	train-mlogloss:0.56390	eval-mlogloss:0.54059
[100]	train-mlogloss:0.56191	eval-mlogloss:0.53886
[101]	train-mlogloss:0.55985	eval-mlogloss:0.53663
[102]	train-mlogloss:0.55643	eval-mlogloss:0.53305
[103]	train-mlogloss:0.55290	eval-mlogloss:0.52926
[104]	train-mlogloss:0.54929	eval-mlogloss:0.52571
[105]	train-mlogloss:0.54582	eval-mlogloss:0.52169
[106]	train-mlogloss:0.54194	eval-mlogloss:0.51727
[107]	train-mlogloss:0.54008	eval-mlogloss:0.51514
[108]	train-mlogloss:0.53693	eval-mlogloss:0.51195
[109]	train-mlogloss:0.53416	eval-mlogloss:0.50901
[110]	train-mlogloss:0.53187	eval-mlogloss:0.50633
[111]	train-mlogloss:0.52721	eval-mlogloss:0.50115
[112]	train-mlogloss:0.52435	eval-mlogloss:0.49800
[113]	train-mlogloss:0.52171	eval-mlogloss:0.49479
[114]	train-mlogloss:0.51858	eval-mlogloss:0.49112
[115]	train-mlogloss:0.51531	eval-mlogloss:0.48719
[116]	train-mlogloss:0.51375	eval-mlogloss:0.48554
[117]	train-mlogloss:0.51027	eval-mlogloss:0.48170
[118]	train-mlogloss:0.50967	eval-mlogloss:0.48114
[119]	train-mlogloss:0.50703	eval-mlogloss:0.47812
[120]	train-mlogloss:0.50415	eval-mlogloss:0.47472
[121]	train-mlogloss:0.49990	eval-mlogloss:0.46996
[122]	train-mlogloss:0.49780	eval-mlogloss:0.46768
[123]	train-mlogloss:0.49555	eval-mlogloss:0.46518
[124]	train-mlogloss:0.49299	eval-mlogloss:0.46256
[125]	train-mlogloss:0.49136	eval-mlogloss:0.46086
[126]	train-mlogloss:0.48852	eval-mlogloss:0.45789
[127]	train-mlogloss:0.48604	eval-mlogloss:0.45535
[128]	train-mlogloss:0.48267	eval-mlogloss:0.45149
[129]	train-mlogloss:0.47948	eval-mlogloss:0.44807
[130]	train-mlogloss:0.47580	eval-mlogloss:0.44419
[131]	train-mlogloss:0.47345	eval-mlogloss:0.44151
[132]	train-mlogloss:0.47054	eval-mlogloss:0.43836
[133]	train-mlogloss:0.46955	eval-mlogloss:0.43737
[134]	train-mlogloss:0.46685	eval-mlogloss:0.43425
[135]	train-mlogloss:0.46453	eval-mlogloss:0.43178
[136]	train-mlogloss:0.46198	eval-mlogloss:0.42888
[137]	train-mlogloss:0.45926	eval-mlogloss:0.42587
[138]	train-mlogloss:0.45626	eval-mlogloss:0.42244
[139]	train-mlogloss:0.45479	eval-mlogloss:0.42095
[140]	train-mlogloss:0.45270	eval-mlogloss:0.41852
[141]	train-mlogloss:0.45004	eval-mlogloss:0.41561
[142]	train-mlogloss:0.44827	eval-mlogloss:0.41364
[143]	train-mlogloss:0.44620	eval-mlogloss:0.41131
[144]	train-mlogloss:0.44364	eval-mlogloss:0.40846
[145]	train-mlogloss:0.44185	eval-mlogloss:0.40655
[146]	train-mlogloss:0.43888	eval-mlogloss:0.40310
[147]	train-mlogloss:0.43637	eval-mlogloss:0.40026
[148]	train-mlogloss:0.43406	eval-mlogloss:0.39779
[149]	train-mlogloss:0.43182	eval-mlogloss:0.39521
[150]	train-mlogloss:0.43046	eval-mlogloss:0.39368
[151]	train-mlogloss:0.42882	eval-mlogloss:0.39187
[152]	train-mlogloss:0.42570	eval-mlogloss:0.38821
[153]	train-mlogloss:0.42421	eval-mlogloss:0.38657
[154]	train-mlogloss:0.42155	eval-mlogloss:0.38368
[155]	train-mlogloss:0.41963	eval-mlogloss:0.38144
[156]	train-mlogloss:0.41810	eval-mlogloss:0.37974
[157]	train-mlogloss:0.41504	eval-mlogloss:0.37633
[158]	train-mlogloss:0.41190	eval-mlogloss:0.37281
[159]	train-mlogloss:0.41060	eval-mlogloss:0.37157
[160]	train-mlogloss:0.41013	eval-mlogloss:0.37107
[161]	train-mlogloss:0.40938	eval-mlogloss:0.37028
[162]	train-mlogloss:0.40734	eval-mlogloss:0.36787
[163]	train-mlogloss:0.40691	eval-mlogloss:0.36755
[164]	train-mlogloss:0.40427	eval-mlogloss:0.36447
[165]	train-mlogloss:0.40355	eval-mlogloss:0.36383
[166]	train-mlogloss:0.40160	eval-mlogloss:0.36169
[167]	train-mlogloss:0.39965	eval-mlogloss:0.35946
[168]	train-mlogloss:0.39811	eval-mlogloss:0.35780
[169]	train-mlogloss:0.39604	eval-mlogloss:0.35540
[170]	train-mlogloss:0.39396	eval-mlogloss:0.35322
[171]	train-mlogloss:0.39285	eval-mlogloss:0.35184
[172]	train-mlogloss:0.39085	eval-mlogloss:0.34954
[173]	train-mlogloss:0.38930	eval-mlogloss:0.34784
[174]	train-mlogloss:0.38801	eval-mlogloss:0.34622
[175]	train-mlogloss:0.38649	eval-mlogloss:0.34454
[176]	train-mlogloss:0.38537	eval-mlogloss:0.34344
[177]	train-mlogloss:0.38459	eval-mlogloss:0.34248
[178]	train-mlogloss:0.38269	eval-mlogloss:0.34033
[179]	train-mlogloss:0.38073	eval-mlogloss:0.33817
[180]	train-mlogloss:0.37836	eval-mlogloss:0.33551
[181]	train-mlogloss:0.37687	eval-mlogloss:0.33392
[182]	train-mlogloss:0.37539	eval-mlogloss:0.33222
[183]	train-mlogloss:0.37396	eval-mlogloss:0.33088
[184]	train-mlogloss:0.37231	eval-mlogloss:0.32922
[185]	train-mlogloss:0.37137	eval-mlogloss:0.32819
[186]	train-mlogloss:0.37072	eval-mlogloss:0.32756
[187]	train-mlogloss:0.36952	eval-mlogloss:0.32621
[188]	train-mlogloss:0.36854	eval-mlogloss:0.32512
[189]	train-mlogloss:0.36731	eval-mlogloss:0.32380
[190]	train-mlogloss:0.36591	eval-mlogloss:0.32224
[191]	train-mlogloss:0.36538	eval-mlogloss:0.32151
[192]	train-mlogloss:0.36419	eval-mlogloss:0.32039
[193]	train-mlogloss:0.36300	eval-mlogloss:0.31904
[194]	train-mlogloss:0.36212	eval-mlogloss:0.31807
[195]	train-mlogloss:0.36055	eval-mlogloss:0.31626
[196]	train-mlogloss:0.35891	eval-mlogloss:0.31436
[197]	train-mlogloss:0.35799	eval-mlogloss:0.31347
[198]	train-mlogloss:0.35702	eval-mlogloss:0.31240
[199]	train-mlogloss:0.35567	eval-mlogloss:0.31082
[200]	train-mlogloss:0.35470	eval-mlogloss:0.30991
[201]	train-mlogloss:0.35423	eval-mlogloss:0.30941
[202]	train-mlogloss:0.35313	eval-mlogloss:0.30829
[203]	train-mlogloss:0.35107	eval-mlogloss:0.30580
[204]	train-mlogloss:0.34999	eval-mlogloss:0.30469
[205]	train-mlogloss:0.34773	eval-mlogloss:0.30212
[206]	train-mlogloss:0.34604	eval-mlogloss:0.30030
[207]	train-mlogloss:0.34493	eval-mlogloss:0.29920
[208]	train-mlogloss:0.34473	eval-mlogloss:0.29905
[209]	train-mlogloss:0.34359	eval-mlogloss:0.29785
[210]	train-mlogloss:0.34324	eval-mlogloss:0.29752
[211]	train-mlogloss:0.34201	eval-mlogloss:0.29626
[212]	train-mlogloss:0.34074	eval-mlogloss:0.29475
[213]	train-mlogloss:0.33968	eval-mlogloss:0.29354
[214]	train-mlogloss:0.33816	eval-mlogloss:0.29175
[215]	train-mlogloss:0.33712	eval-mlogloss:0.29060
[216]	train-mlogloss:0.33591	eval-mlogloss:0.28926
[217]	train-mlogloss:0.33434	eval-mlogloss:0.28740
[218]	train-mlogloss:0.33322	eval-mlogloss:0.28613
[219]	train-mlogloss:0.33212	eval-mlogloss:0.28493
[220]	train-mlogloss:0.33082	eval-mlogloss:0.28346
[221]	train-mlogloss:0.33021	eval-mlogloss:0.28277
[222]	train-mlogloss:0.32842	eval-mlogloss:0.28092
[223]	train-mlogloss:0.32795	eval-mlogloss:0.28048
[224]	train-mlogloss:0.32624	eval-mlogloss:0.27857
[225]	train-mlogloss:0.32572	eval-mlogloss:0.27819
[226]	train-mlogloss:0.32496	eval-mlogloss:0.27745
[227]	train-mlogloss:0.32349	eval-mlogloss:0.27589
[228]	train-mlogloss:0.32271	eval-mlogloss:0.27494
[229]	train-mlogloss:0.32233	eval-mlogloss:0.27453
[230]	train-mlogloss:0.32121	eval-mlogloss:0.27331
[231]	train-mlogloss:0.32009	eval-mlogloss:0.27202
[232]	train-mlogloss:0.31957	eval-mlogloss:0.27150
[233]	train-mlogloss:0.31838	eval-mlogloss:0.27030
[234]	train-mlogloss:0.31678	eval-mlogloss:0.26847
[235]	train-mlogloss:0.31635	eval-mlogloss:0.26814
[236]	train-mlogloss:0.31531	eval-mlogloss:0.26720
[237]	train-mlogloss:0.31402	eval-mlogloss:0.26586
[238]	train-mlogloss:0.31371	eval-mlogloss:0.26543
[239]	train-mlogloss:0.31329	eval-mlogloss:0.26505
[240]	train-mlogloss:0.31275	eval-mlogloss:0.26432
[241]	train-mlogloss:0.31202	eval-mlogloss:0.26359
[242]	train-mlogloss:0.31192	eval-mlogloss:0.26359
[243]	train-mlogloss:0.31152	eval-mlogloss:0.26317
[244]	train-mlogloss:0.31059	eval-mlogloss:0.26203
[245]	train-mlogloss:0.30959	eval-mlogloss:0.26096
[246]	train-mlogloss:0.30937	eval-mlogloss:0.26075
[247]	train-mlogloss:0.30848	eval-mlogloss:0.25981
[248]	train-mlogloss:0.30733	eval-mlogloss:0.25855
[249]	train-mlogloss:0.30647	eval-mlogloss:0.25754
[250]	train-mlogloss:0.30564	eval-mlogloss:0.25658
[251]	train-mlogloss:0.30545	eval-mlogloss:0.25628
[252]	train-mlogloss:0.30461	eval-mlogloss:0.25535
[253]	train-mlogloss:0.30457	eval-mlogloss:0.25526
[254]	train-mlogloss:0.30331	eval-mlogloss:0.25386
[255]	train-mlogloss:0.30296	eval-mlogloss:0.25350
[256]	train-mlogloss:0.30218	eval-mlogloss:0.25262
[257]	train-mlogloss:0.30072	eval-mlogloss:0.25099
[258]	train-mlogloss:0.30006	eval-mlogloss:0.25014
[259]	train-mlogloss:0.29942	eval-mlogloss:0.24945
[260]	train-mlogloss:0.29830	eval-mlogloss:0.24818
[261]	train-mlogloss:0.29696	eval-mlogloss:0.24676
[262]	train-mlogloss:0.29677	eval-mlogloss:0.24669
[263]	train-mlogloss:0.29552	eval-mlogloss:0.24538
[264]	train-mlogloss:0.29465	eval-mlogloss:0.24430
[265]	train-mlogloss:0.29448	eval-mlogloss:0.24415
[266]	train-mlogloss:0.29373	eval-mlogloss:0.24323
[267]	train-mlogloss:0.29324	eval-mlogloss:0.24267
[268]	train-mlogloss:0.29238	eval-mlogloss:0.24170
[269]	train-mlogloss:0.29177	eval-mlogloss:0.24101
[270]	train-mlogloss:0.29085	eval-mlogloss:0.24000
[271]	train-mlogloss:0.29022	eval-mlogloss:0.23921
[272]	train-mlogloss:0.28943	eval-mlogloss:0.23841
[273]	train-mlogloss:0.28891	eval-mlogloss:0.23773
[274]	train-mlogloss:0.28800	eval-mlogloss:0.23681
[275]	train-mlogloss:0.28738	eval-mlogloss:0.23610
[276]	train-mlogloss:0.28734	eval-mlogloss:0.23604
[277]	train-mlogloss:0.28637	eval-mlogloss:0.23499
[278]	train-mlogloss:0.28574	eval-mlogloss:0.23433
[279]	train-mlogloss:0.28514	eval-mlogloss:0.23370
[280]	train-mlogloss:0.28457	eval-mlogloss:0.23289
[281]	train-mlogloss:0.28401	eval-mlogloss:0.23226
[282]	train-mlogloss:0.28400	eval-mlogloss:0.23224
[283]	train-mlogloss:0.28347	eval-mlogloss:0.23149
[284]	train-mlogloss:0.28339	eval-mlogloss:0.23154
[285]	train-mlogloss:0.28317	eval-mlogloss:0.23134
[286]	train-mlogloss:0.28255	eval-mlogloss:0.23059
[287]	train-mlogloss:0.28251	eval-mlogloss:0.23052
[288]	train-mlogloss:0.28199	eval-mlogloss:0.22999
[289]	train-mlogloss:0.28103	eval-mlogloss:0.22882
[290]	train-mlogloss:0.28051	eval-mlogloss:0.22818
[291]	train-mlogloss:0.27990	eval-mlogloss:0.22742
[292]	train-mlogloss:0.27981	eval-mlogloss:0.22740
[293]	train-mlogloss:0.27926	eval-mlogloss:0.22682
[294]	train-mlogloss:0.27906	eval-mlogloss:0.22660
[295]	train-mlogloss:0.27790	eval-mlogloss:0.22539
[296]	train-mlogloss:0.27782	eval-mlogloss:0.22545
[297]	train-mlogloss:0.27731	eval-mlogloss:0.22494
[298]	train-mlogloss:0.27681	eval-mlogloss:0.22438
[299]	train-mlogloss:0.27658	eval-mlogloss:0.22428

[I 2025-06-27 22:41:32,800] Trial 41 finished with value: 1.0 and parameters: {'lambda': 8.97683751998338e-06, 'alpha': 0.23657189127064443, 'eta': 0.010136320663347907, 'gamma': 2.45194707194023e-06, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.6881823860350011, 'colsample_bytree': 0.4758743708969564}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08478	eval-mlogloss:1.08398
[1]	train-mlogloss:1.07783	eval-mlogloss:1.07638
[2]	train-mlogloss:1.06847	eval-mlogloss:1.06799
[3]	train-mlogloss:1.05267	eval-mlogloss:1.05113
[4]	train-mlogloss:1.04619	eval-mlogloss:1.04371
[5]	train-mlogloss:1.03564	eval-mlogloss:1.03263
[6]	train-mlogloss:1.02039	eval-mlogloss:1.01638
[7]	train-mlogloss:1.00408	eval-mlogloss:0.99870
[8]	train-mlogloss:0.99618	eval-mlogloss:0.99147

[I 2025-06-27 22:41:32,880] Trial 42 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03696	eval-mlogloss:1.03407
[1]	train-mlogloss:1.00494	eval-mlogloss:1.00190

[I 2025-06-27 22:41:32,948] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07067	eval-mlogloss:1.06915
[1]	train-mlogloss:1.05714	eval-mlogloss:1.05269
[2]	train-mlogloss:1.03892	eval-mlogloss:1.03625
[3]	train-mlogloss:1.00826	eval-mlogloss:1.00345
[4]	train-mlogloss:0.99648	eval-mlogloss:0.99088
[5]	train-mlogloss:0.97625	eval-mlogloss:0.97098
[6]	train-mlogloss:0.94810	eval-mlogloss:0.94090
[7]	train-mlogloss:0.91975	eval-mlogloss:0.91090
[8]	train-mlogloss:0.90626	eval-mlogloss:0.89807

[I 2025-06-27 22:41:33,026] Trial 44 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03322	eval-mlogloss:1.03033
[1]	train-mlogloss:0.99701	eval-mlogloss:0.99508

[I 2025-06-27 22:41:33,095] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97774	eval-mlogloss:0.97362
[1]	train-mlogloss:0.92508	eval-mlogloss:0.91593
[2]	train-mlogloss:0.83967	eval-mlogloss:0.82385

[I 2025-06-27 22:41:33,165] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08851	eval-mlogloss:1.08799
[1]	train-mlogloss:1.08335	eval-mlogloss:1.08228
[2]	train-mlogloss:1.07675	eval-mlogloss:1.07635
[3]	train-mlogloss:1.06531	eval-mlogloss:1.06417
[4]	train-mlogloss:1.06004	eval-mlogloss:1.05885
[5]	train-mlogloss:1.05197	eval-mlogloss:1.05038
[6]	train-mlogloss:1.04024	eval-mlogloss:1.03747
[7]	train-mlogloss:1.02824	eval-mlogloss:1.02446
[8]	train-mlogloss:1.02254	eval-mlogloss:1.01926
[9]	train-mlogloss:1.01035	eval-mlogloss:1.00661
[10]	train-mlogloss:1.00154	eval-mlogloss:0.99719
[11]	train-mlogloss:0.99651	eval-mlogloss:0.99290
[12]	train-mlogloss:0.98630	eval-mlogloss:0.98169
[13]	train-mlogloss:0.97809	eval-mlogloss:0.97328
[14]	train-mlogloss:0.96687	eval-mlogloss:0.96107
[15]	train-mlogloss:0.96024	eval-mlogloss:0.95462
[16]	train-mlogloss:0.95458	eval-mlogloss:0.94793
[17]	train-mlogloss:0.94579	eval-mlogloss:0.93931
[18]	train-mlogloss:0.93698	eval-mlogloss:0.93010
[19]	train-mlogloss:0.93421	eval-mlogloss:0.92716
[20]	train-mlogloss:0.93135	eval-mlogloss:0.92444
[21]	train-mlogloss:0.92362	eval-mlogloss:0.91646
[22]	train-mlogloss:0.91298	eval-mlogloss:0.90475
[23]	train-mlogloss:0.90234	eval-mlogloss:0.89355
[24]	train-mlogloss:0.89323	eval-mlogloss:0.88375
[25]	train-mlogloss:0.88314	eval-mlogloss:0.87308
[26]	train-mlogloss:0.88082	eval-mlogloss:0.87093
[27]	train-mlogloss:0.87223	eval-mlogloss:0.86184
[28]	train-mlogloss:0.86680	eval-mlogloss:0.85664
[29]	train-mlogloss:0.86122	eval-mlogloss:0.85098
[30]	train-mlogloss:0.85681	eval-mlogloss:0.84701
[31]	train-mlogloss:0.84947	eval-mlogloss:0.83938

[I 2025-06-27 22:41:33,368] Trial 47 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:0.77111	eval-mlogloss:0.75766
[1]	train-mlogloss:0.56841	eval-mlogloss:0.54006

[I 2025-06-27 22:41:33,444] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88526	eval-mlogloss:0.88879
[1]	train-mlogloss:0.72352	eval-mlogloss:0.71601

[I 2025-06-27 22:41:33,511] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 3.8824678601102815e-06, 'alpha': 6.721789534672643e-08, 'eta': 0.2070189698398038, 'gamma': 0.0017096393792721705, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.7134122274307897, 'colsample_bytree': 0.554105712470375}
Best accuracy: 1.0

In [40]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()